### ISSUE TITLE
Support custom folder order

### ISSUE THREAD

**Issue by gtandersen** [runbox/runbox7#1002]
Add the ability to move folders into custom positions in the folder pane.

This could be accompanied by a button for resetting the order to alphabetical.

**Comment by castaway** [comment]
Re-ordering of folders was already 99% implemented, just the top level "display in saved order" was broken, so I've patched it in #1040

**Comment by castaway** [comment]
Oops, my fix for this has a bug: Newly created folders (which get a priority of 0 at the moment) - get sorted above "Inbox" in the folder list..

**Comment by castaway** [comment]
Fixed in #1282
