### ISSUE TITLE
Prevent existing customers from downgrading to plans that would cause them to go over quotas

### ISSUE THREAD

**Issue by runboxdave** [runbox/runbox7#1014]
Prevent existing customers from downgrading to plans that would caused them to go over quotas.

This can be quite detrimental to an account as it can immediately cause it to go over quota and stop receiving messages.

The two relevant quotas are storage an the number of email hosting domains allowed.

**Comment by gtandersen** [comment]
Additionally we should alert existing accounts that are over any quota that they need to upgrade to keep the items over the current quota.

**Comment by castaway** [comment]
On runbox.com/app/account/plans at the top, we display (as a smallish note) how much disc space the main account is using up, we currently offer to up/downgrade to any other account (mini, medium max etc) regardless of quota used.

We should 
1) Sync quota when loading this page to ensure its correct (see admin pages for a way to do this)
2) send more data to the list of accounts shown so we can either hide or warn for plans which would put the user over quota

**Comment by castaway** [comment]
Add "quota" to the returned/suggested subscription data), then compare on the frontend (should be fairly straight forward)
