### ISSUE TITLE
Make "View Original HTML" do what it says

### ISSUE THREAD

**Issue by gtandersen** [runbox/runbox7#1018]
When clicking View Original HTML the same sanitized version of the HTML message is shown in a separate tab.

This is useful, but it could be be renamed to "Open in new tab" or similar, and another option "View Original HTML" can be added which actually does what it says (with a warning).

**Comment by gtandersen** [comment]
Since this issue was created, and possibly in relation to #1252, the Original HTML option now does not show inline images and there is no way to make it do that.

**Comment by castaway** [comment]
Original HTML  seems to be displaying all images for me - either I literally just fixed it with the update (though I thought I'd done it a while ago) - or you have some message specific issue. Retry please?

**Comment by gtandersen** [comment]
Confirmed to work in the latest version!
