### ISSUE TITLE
Certain emails don't open

### ISSUE THREAD

**Issue by VSirvio** [runbox/runbox7#1065]
Certain kind of automatic emails refuse to open in Runbox 7. When clicked, they only show a blank preview pane. In Runbox 6, they work fine. See an example of such a message below:

[message.txt](https://github.com/runbox/runbox7/files/7013090/message.txt)

OS: Windows 10 Home
Browser: Firefox 91.0.1 (64-bit)
Local index: Yes

**Comment by gtandersen** [comment]
See also #1166.
