### ISSUE TITLE
Can't scroll horizontally in message view

### ISSUE THREAD

**Issue by gtandersen** [runbox/runbox7#1072]
When viewing an HTML or preformatted message in vertical mode (Firefox on macOS), the horizontal scrollbar isn't visible and it's not possible to scroll horizontally.

**Comment by kvviecien** [comment]
In Vertical Preview, the message normally wraps in the container. I never saw a horizontal scrollbar there. 
Do you mean a scrollbar in message view or in message list view?

**Comment by gtandersen** [comment]
Correct, the message contents usually wraps but in some cases HTML or preformatted messages don't wrap.

Example from Firefox on macOS (no vertical scrollbar is shown either as it disappears before a screenshot can be made):

<img width="481" alt="Message view no horizontal scrollbar" src="https://user-images.githubusercontent.com/1620058/132955473-c0fbd466-5f7c-4cda-ad56-529488c6a1cb.png">

The message is https://runbox.com/app/#Inbox:12146287 in the test account.

**Comment by piratefinn** [comment]
Can confirm the lack of a horizontal scrollbar when I have a HTML message previewed on Windows 10 with Chrome after horizontally resizing the preview frame.
