### ISSUE TITLE
Always show message view options

### ISSUE THREAD

**Issue by gtandersen** [runbox/runbox7#1078]
The message view options menu items depend on the use of the local index.

**With index:**
<img width="274" alt="Message view options with index" src="https://user-images.githubusercontent.com/1620058/132955172-91711a80-6c5e-42a2-bb58-941eeeb35578.png">

**Without index:**
<img width="276" alt="Message view options without index" src="https://user-images.githubusercontent.com/1620058/132955171-5dbf507f-e2d3-4116-9f3c-1ff6583468d5.png">

This can be confusing and we could instead show all options regardless, but when the local index is not in use gray out disabled options with a tooltip explaining that these options are only available when the index is in use.

**Comment by piratefinn** [comment]
@gtandersen confirm this is fixed with [this PR](https://github.com/runbox/runbox7/issues/1078) ?

**Comment by gtandersen** [comment]
@piratefinn Thanks; confirmed and closing issue.
