### ISSUE TITLE
Email composing Recipient address issue when involving Contacts

### ISSUE THREAD

**Issue by piratefinn** [runbox/runbox7#1079]
Issue on Chrome 93 Windows

To repeat the issue:
1. Type in a recipient address and get a suggested contact, click to use that contact to auto fill it in
2. Delete that filled in address
3. Type in an email address to send to (such as test@example.com)
4. Leave focus of that text entry by clicking elsewhere, such as the next entry box or pressing tab.

Expected behaviour is that leaving focus of the Recipient address entry should "auto enter" in the sense that it treats the user having confirmed using that address, like pressing enter manually would. However by following the above which I had coincidentally done while testing another issue, that issue becomes present. It caught me off guard as I did essentially that, then pressed to send a mail, then got told no recipient because it had not automatically confirmed the recipient entry.

**Comment by gtandersen** [comment]
Agreed @piratefinn, and to clarify the issue can be reproduced simply by following stepd 3 and 4 above.
