### ISSUE TITLE
Improve visibility of Folder column in searches

### ISSUE THREAD

**Issue by gtandersen** [runbox/runbox7#1083]
When searching for messages (with local index) an extra Folder column is added to the message list showing which folder each message is found in.

However, the column is (often) shown to the right of the browser window and is therefore invisible:

<img width="863" alt="Search Folder column invisible" src="https://user-images.githubusercontent.com/1620058/133805520-68b383e5-535c-427e-843b-9f16b81e04ad.png">

...until the Size column is dragged to the left:

<img width="864" alt="Search Folder column visible" src="https://user-images.githubusercontent.com/1620058/133805750-ab813c3d-0ddc-4615-9f12-1c1ef2f9d3eb.png">

This should be improved so that the Folder column is visible immediately.

Additionally, the contents of the Folders column is often trimmed so that only the  first part of the folder name is visible. Because the width of the folder column can't be adjusted manually there is no way for the user to make the full folder names visible:

<img width="335" alt="Search Folder column trimmed" src="https://user-images.githubusercontent.com/1620058/133806336-db447655-4586-4e53-bdcf-2b885d0373aa.png">

With longer (sub)folder names this becomes unusable. The entire available width should be used to show content, and it should be possible to adjust the right-hand column divider of the rightmost column.

Browser used: Firefox on macOS.

**Comment by castaway** [comment]
Poked around a bit, the default looks a bit different for me, I managed to see 20 odd characters of the folder name, on a fullscreen desktop view, no view pane open - did you have yours open? However there's definitely some weirdness in calculating the canvas / scroll-bar-needed widths. 

After I opened the mail pane then closed it again, I couldn't get the columns to take up the full width again, not even after refreshing the page - I'll keep poking
