### ISSUE TITLE
Clicking to stop or start synchronization hides folder pane

### ISSUE THREAD

**Issue by gtandersen** [runbox/runbox7#109]
When clicking "Synchronize index" or "Stop index synchronization", the folder pane is hidden and the user must click the menu icon to make it reappear.

**Comment by petersalomonsen** [comment]
Should be just to remove the `sidemenu.close()` from here:

https://github.com/runbox/runbox7/blob/master/src/app/app.component.html#L55

and here:

https://github.com/runbox/runbox7/blob/master/src/app/app.component.html#L63

**Comment by gtandersen** [comment]
Thanks @petersalomonsen -- see https://github.com/runbox/runbox7/pull/127.
