### ISSUE TITLE
Incorrect redirect for https://runbox.com/app/account/subscriptions when logged out.

### ISSUE THREAD

**Issue by runboxdave** [runbox/runbox7#1097]
https://runbox.com/app/account/subscriptions redirects to https://runbox.com/app/login when not logged in and from here logging in doesn't work with the log in page just stalling and doing nothing much.

This needs an urgent fix as this is the link we supply in renewal emails.

**Comment by gtandersen** [comment]
@hernan604 @castaway Can you look into this urgent issue?

In short we need to retain the destination https://runbox.com/app/account/subscriptions through the login process so that the user is redirected back to the initial URL upon logging in.
