### ISSUE TITLE
Show message action buttons when selecting messages with preview window open

### ISSUE THREAD

**Issue by gtandersen** [runbox/runbox7#11]
When a message is opened and shown in the preview window, the message action buttons aren't shown when messages are selected in the list.

Ref: https://community.runbox.com/t/selecting-scrolling-issues/670

**Comment by kotecky** [comment]
BTW, when rendered on a large screen, the buttons could be located at the edge of the message list and not far right by at the edge of the message preview pane. Which is particularly painful on a laptop with a touchpad.

**Comment by vertigo220** [comment]
Agree 100% with both of these. On a large/wide screen, having the buttons all the way on the right is inefficient, requiring the user to move back and forth quite a bit. The buttons definitely need to show when the preview pane is showing, and they should ideally be in a better location, which would also help with the first issue. They should probably be either at the top or bottom of the message list, or maybe even between the folder and message list.

**Comment by gtandersen** [comment]
This is fixed.
