### ISSUE TITLE
When dragging/moving messages the one you drag is deselected

### ISSUE THREAD

**Issue by runboxdave** [runbox/runbox7#1122]
When you select multiple messages and drag them to another folder, the one you actually put the mouse on to drag is deselected and not moved.

**Describe the bug**
Moving multiple messages with drag and drop deselects the dragged message. 

**To Reproduce**
1. Go to https://runbox.com/app
2. Click to select 2 or more messages
3. Drag the subject line of either message to another folder
4. Observe that the dragged message is deselected and not moved

**Expected behavior**
All selected messages should be moved.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Firefox

**Comment by gtandersen** [comment]
See also #1095.
