### ISSUE TITLE
Size and Folder columns work inconsistently

### ISSUE THREAD

**Issue by gtandersen** [runbox/runbox7#1126]
**Describe the bug**
The Size and Folder columns work somewhat inconsistently especially in Safari after the improvements in #1115.

**To Reproduce**
1. Go to https://runbox.com/app
2. Ensure the local index is in use.
3. Observe the following, as seen in the screenshots below:
 - The Size column heading is offset relative to the column content.
 - After entering a search term to bring up the Folder column in the message list, some of the longer the folder names are truncated and the Folder column can't be expanded to view the entire contents.
 - Similarly, the Folder column heading can't be slid all the way to the left next to the Size and flag/attachment columns. 

**Expected behavior**
The columns and their headings should be more flexible to allow the fullest possible use of the horizontal space.

**Screenshots**

<img width="919" alt="Runbox 7 Size column heading offset Safari" src="https://user-images.githubusercontent.com/1620058/141159463-7e5893d3-07e9-43e1-b4a4-328db0790ca8.png">

<img width="930" alt="Runbox 7 truncated folder name" src="https://user-images.githubusercontent.com/1620058/141159492-dd6453a4-3c09-4ffe-8915-f9a5b409b2a6.png">

https://user-images.githubusercontent.com/1620058/141159511-91dda939-a5ce-4298-b4bd-72d3139968f4.mov

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Safari

**Comment by castaway** [comment]
Between "Size" and "Folder" are 3 other columns: Attachment(s), Answered and Flagged - maybe we should give these titles so that its more obvious? The current code does not allow a column to get smaller than 40px width (wide enough for the single character/icon in the flag columns). Dragging or resizing the Folder column left is actually resizing the Flagged column, thus it can't get any smaller to the left (currently).

Any thoughts on the preferred functionality given the above?

**Comment by gtandersen** [comment]
Might it be a solution to merge the Attachment(s), Answered, and Flagged columns into one, since they probably don't need column headings (for sorting)?

**Comment by castaway** [comment]
With a min-width of what though? 120 so all three icons fit? Or 40 and user must resize it to see them all if wanted?

**Comment by gtandersen** [comment]
Ideally dynamic to fit the icons that are present in the list; otherwise safest to fit all three icons. :)
