### ISSUE TITLE
Body textarea in compose window

### ISSUE THREAD

**Issue by kotecky** [runbox/runbox7#1151]
The body input textarea in compose window has a wrong size (small instead of spanning across the whole width) since the last release across browsers (tested under Win10 in Chrome and FF, in FF under Android).

![image](https://user-images.githubusercontent.com/2297444/146002956-6f7ad342-71ef-4b00-b3ec-0fb20b52926c.png)

**Comment by gtandersen** [comment]
This was fixed in #1153 .
