### ISSUE TITLE
Runbox7 is vulnerable to Reverse Tabnabbing

### ISSUE THREAD

**Issue by rodrigolm** [runbox/runbox7#116]
Hi, there!

I'm following up to your blog post announcing Run Box Bug Bounty Program and I would like to report a vulnerability.

### Description:
Runbox is vulnerable to Reverse Tabnabbing [1]. When a user receives an e-mail with a link, Runbox 7 autogenerates a clickable link with the target="_blank" property. Which at first sight may seem harmless to the user but it can be an malicious link that after clicking on it the malicious page is able to rewrite the original Runbox page, redirecting the user to a phishing site in order to gather credentials.

### Steps to reproduce:
1. Send any e-mail to the victim on Runbox 7 webmail with the following text:
https://s3-us-west-2.amazonaws.com/b33cf3df36b322feb5d38db6d7819561/runbox_tabnabbing.html

2. Log in Runbox 7 with the victim account and click on the link.

3. A new tab/window will be openned with the link while the original Runbox 7 Webmail page will be redirected to a phishing page stating that the session has expired and asking the user to submit the credentials again.

### Impact:
This vulnerability can make Runbox 7 users targets of phishing campaigns to steal their credentials.

### Suggestion to prevent this issue:
In order to mitigate this issue, developers are encouraged to use the property: `rel="nofollow noopener noreferrer"`. With that, when you click on the link, the attacker cannot access the initial tab.

### References:
[1] https://www.owasp.org/index.php/Reverse_Tabnabbing

### Related issues reported to other platforms:
https://hackerone.com/reports/179568
https://hackerone.com/reports/306414
https://hackerone.com/reports/227833
https://hackerone.com/reports/211065

### Sample e-mail:
![runbox_poc](https://user-images.githubusercontent.com/4250445/55685874-4bb60380-5931-11e9-8729-f9baddbec841.png)
:

**Comment by gtandersen** [comment]
Thanks @rodrigolm for the detailed report! A fix is in the pipeline as per the above comments.

Please contact us via https://support.runbox.com and reference this issue for details on the bounty for reporting this vulnerability.

**Comment by rodrigolm** [comment]
Thanks for your reply @gtandersen !

In case you need, here is the **Ticket ID: DWP-135-19051**.
