### ISSUE TITLE
Sent message list incomplete after sending message

### ISSUE THREAD

**Issue by gtandersen** [runbox/runbox7#1167]
**Describe the bug**
When not using the local index and opening the Sent folder after sending a message, only the most recently sent message is visible. The rest of the message list is shown after clicking to another folder and back again.

**To Reproduce**
1. Go to https://runbox.com/app/compose
2. Send a message
3. Click on the Sent folder
4. Observe that only the most recently sent message is visible

**Expected behavior**
The Sent folder should display all sent messages.

**Screenshots**

<img width="1216" alt="Sent messages" src="https://user-images.githubusercontent.com/1620058/148786667-57e52bdb-affe-4110-accc-6979e0318af5.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Safari

**Comment by castaway** [comment]
Fix merged + deployed
