### ISSUE TITLE
Messages with timestamp out of range halts index sync

### ISSUE THREAD

**Issue by gtandersen** [runbox/runbox7#1178]
**Describe the bug**
Messages with a timestamp out of index range (such as 1970 or 2038) causes the index synchronization process to halt.

**To Reproduce**
1. Go to https:/runbox.com/app in an account with one or more messages with an out of range timestamp
2. Wait for the index synchronization to start
3. Observe that the synchronization process never finishes

**Expected behavior**
The synchronization process should finish without pause.

**Comment by castaway** [comment]
See also #1052
