### ISSUE TITLE
Spam and Trash message counters are incorrect 

### ISSUE THREAD

**Issue by gtandersen** [runbox/runbox7#1182]
**Describe the bug**
The Spam and Trash message counters sometimes show more than 0, but no messages are displayed in the list.

**To Reproduce**
1. Go to https://runbox.com/app
2. Observe the Spam and Trash message counts
3. Compare counts that are larger than 0 with the actual contents in the folders

**Expected behavior**
The Spam and Trash folders should always show the correct message counts.

See also #512.

**Comment by castaway** [comment]
I have added a PR (and matching backend fix) that corrects the issue - that is the regular runbox7 polling/data update will check if the spam+trash counts on display match the counts in the folder, and trigger the backend to update them if they don't.

This doesn't find or fix the underlying problem of when/how they end up being incorrect in the first place.
