### ISSUE TITLE
Messages can not be deleted from the list with INBOX vs Inbox mismatch (without local index) 

### ISSUE THREAD

**Issue by gtandersen** [runbox/runbox7#1197]
**Describe the bug**
After importing a number of messages via IMAP and attempting to delete a message using the message action menu buttons, no response is visible in the app.

**To Reproduce**
1. Import a number of email via IMAP
2. Go to https://runbox.com/app
3. Select a message in the list and click to delete it
4. Observe that no response is given in the app
5. Observe the following error in the console: 
`TypeError: i.folderCounts[r.folder] is undefined`

**Expected behavior**
The selected message should be deleted when clicking the delete/trash button.

**Comment by runboxdave** [comment]
When trying to delete the same messages that have been imported via IMAP using a checkbox and the floating mail list menu delete button the message disappears and then re-appears a few seconds later. So the same result is the outcome but it looks different to the user as at least something happens.

**Comment by runboxdave** [comment]
After further investigation it seems that this problem is related to the messages being assigned to a folder called INBOX rather than Inbox. The messages that were in INBOX were imported using Apple Mail (whether this applies to other email clients or the Runbox IMAP Import is not known yet).

**Comment by castaway** [comment]
Have confirmed that importing messages via Claws Mail creates the same issue (INBOX folder not Inbox, and can't delete)

**Comment by gtandersen** [comment]
This is related to #69 and internal issue 978.

**Comment by rootwork** [comment]
I'm seeing this same behavior (as the OP) as well. @gtandersen you say it's related to #69 but that issue was closed and from what I read in the issue, nothing was done. If #69 is still an active issue, can it be re-opened?

**Comment by castaway** [comment]
#69 was resolved, that ensured we could display messages that're in folder INBOX (as well as Inbox), if you do a search you'll see results from both. It didn't fix the underlying issue though.

**Comment by castaway** [comment]
An idea for fixing this one (or at least papering over it until we get backend import issue sorted): The "verifymessages" system, which is used when api folder counts dont match index folder counts (as they wont with INBOX/Inbox being diffferent) - is used to flag messages with different settings (eg read/unread, flagged etc) for reindexing. We could also have it sort out the folder name too (and flag that for reindexing as well).

**Comment by gtandersen** [comment]
This should hopefully improve with #1215 (right @castaway?).

**Comment by castaway** [comment]
Nope, that one only turns verification back on, would need another for the INBOX/Inbox idea

**Comment by castaway** [comment]
MR submitted to backend to tackle this issue as described above
