### ISSUE TITLE
Printing a message crops content

### ISSUE THREAD

**Issue by gtandersen** [runbox/runbox7#1200]
**Describe the bug**
When printing a message from vertical or horizontal view, half the content is cut off.

**To Reproduce**
1. Go to https://runbox.com/app
2. Click to view a message in vertical or horizontal view
3. Click to print the message
4. Observe that the printed message is cropped to display only half the content.

**Expected behavior**
The entire content of the message should be visible when printed.

**Screenshots**
![76da19865592cab2218290f449a214148285a66d](https://user-images.githubusercontent.com/1620058/153006612-21572da3-1445-44a4-a989-64d34a174211.jpeg)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox 96.0.3

**Comment by kvviecien** [comment]
This seems to be an issue only for HTML messages once they're in "HTML view". Some iframe magic is needed here.
Have you ever tried to print a HTML message before? Wondering what could have changed here.

**Comment by gtandersen** [comment]
I think it could be a "new" issue, but it is not entirely clear when the issue was introduced as I rarely need to print messages. :)
