### ISSUE TITLE
Attachment icon collumn not displayed on result list

### ISSUE THREAD

**Issue by kotecky** [runbox/runbox7#1234]
In normal message lists (inbox, ...) a column with an attachment icon is displayed. The column contain an attachment icon for messages having one. The search result list does not have that column. 

**To Reproduce**
Search any term. See.

**Expected behavior**
The message list displaying the search results should have a column to display whether a message has an attachment or not. 

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: FF
 - Version 98.0.2
The same behaviour on an Android mobile phone.

**Comment by gtandersen** [comment]
@kotecky Could not reproduce this, and should be working correctly after https://github.com/runbox/runbox7/pull/1216.

Can you provide screenshots showing the difference between regular list and search list?

Thanks!

**Comment by kotecky** [comment]
I can ;)  Before a search: 
![image](https://user-images.githubusercontent.com/2297444/161224432-20466acc-67f6-4cf0-b628-78af18d44077.png)
After a search: 
![image](https://user-images.githubusercontent.com/2297444/161224524-22fa17fe-24f3-4f06-84ed-b640384f7dd5.png)

**Comment by gtandersen** [comment]
@kotecky It seems an error was introduced (possibly in #1216) that shows attachment icons as reply icons, and we are working to fix this.

We are also working to only show attachment icons on actual attachments in #1226.
