### ISSUE TITLE
Images can't be included inline in HTML messages unless they are URLs to files hosted on a web server

### ISSUE THREAD

**Issue by runboxdave** [runbox/runbox7#1257]
**Is your feature request related to a problem? Please describe.**
It's not possible to insert images in HTML messages unless they are URLs to images hosted on a website.

**Describe the solution you'd like**
Be able to include images as attachments and insert them inline in messages being composed in HTML mode.

**Describe alternatives you've considered**
None. This is pretty much the expectation of users.

**Additional context**
None

**Comment by castaway** [comment]
See also: #763 and #777

**Comment by gtandersen** [comment]
Inline images in HTML messages used to work after first attaching them (as per https://help.runbox.com/runbox-7-webmail-new-features/#Draft_Desk), but it appears to not work currently.

Either way a better solution would be the ability to drag an image directly into an HTML message, but that action produces this error:

<img width="320" alt="Screen Shot 2022-05-10 at 21 00 32" src="https://user-images.githubusercontent.com/1620058/167702762-59a06d8b-8481-4424-9e71-a22fa3a8a02b.png">
