### ISSUE TITLE
Time zone is inconsistent in Calendar

### ISSUE THREAD

**Issue by gtandersen** [runbox/runbox7#1267]
**Describe the bug**
When adding an event from one timezone and viewing it in another timezone, the latter shows the event without converting or indicating the time zone.

**To Reproduce**
1. Go to https://runbox.com/app/calendar
2. Add an event
4. Change the timezone on the local system
5. Observe that the time for the event is the same

**Expected behavior**
The time of the event should be converted to the new time zone, or the time zone in which it was added should be shown.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Firefox

**Comment by castaway** [comment]
The code is currently setup to use the user's timezone from user settings, as we'd discussed previously. It might be useful to indicate the time in the local / browser timezone as well somehow, if it differs...  any ideas on how that would appear?

**Comment by castaway** [comment]
![2022-08-17 13 21 22 mallet2 scsys co uk a16b6da4275f](https://user-images.githubusercontent.com/109990/185117903-e51d2f90-1bfc-4895-bdcf-7d000e2e07b8.jpg)
![2022-08-17 13 21 08 mallet2 scsys co uk e84fad3d3d15](https://user-images.githubusercontent.com/109990/185117911-d9082367-cdd8-45a6-9465-82391594384b.jpg)
![2022-08-17 13 20 59 mallet2 scsys co uk 7dafacc305ac](https://user-images.githubusercontent.com/109990/185117917-944cce55-3fca-4597-8e25-8b73d9e24910.jpg)

Current suggestion

**Comment by gtandersen** [comment]
This looks good, and in order to integrate further with the rest of the app we could add options such as:

- O Auto-detect timezone
- O Use default app setting (from Personal Details)
- O Use manual time zone:
  -  O CET
  -  O EST
  -  O ETC

**Comment by gtandersen** [comment]
New issue for the above suggestion created in #1305.
