### ISSUE TITLE
Toggling read status is reverted (with local index)

### ISSUE THREAD

**Issue by gtandersen** [runbox/runbox7#1275]
**Describe the bug**
When marking one or more messages as read while using the local index, their state goes back to unread after a short while.

See also #537.

**To Reproduce**
1. Go to https://runbox.com/app and ensure the local index is enabled
2. Click to mark one or more messages as read
3. Wait a short while and they are reverted to unread state

**Expected behavior**
The read state should be maintained.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Firefox

**Comment by lmirguet** [comment]
I encounter the same problem.

- select several messages in a folder
- mark them as read
**- an error message is displayed "Failed to delete multiple emails"**
- then the messages are reverted to their unread status

This is clearly a regression as this feature used to work...

**Comment by lmirguet** [comment]
The bug seems fixed this morning! Thank you!

**Comment by gtandersen** [comment]
Not reproduced since issue was reopened; closing.
