### ISSUE TITLE
Expired accounts get logged out when directed to renew via the "Your Subscriptions" page.

### ISSUE THREAD

**Issue by runboxdave** [runbox/runbox7#1289]
**Describe the bug**

Expired accounts get logged out when directed to renew via the "Your Subscriptions" page (https://runbox.com/app/account/subscriptions). This is not a problem when logging in via Runbox 6 (as far as I can tell at this point).

**To Reproduce**
1. Go to 'https://runbox.com/app'
2. Enter username and password and try to log in.
3. Click on the link to Your Subscriptions when this is presented.

**Expected behavior**
You should be able to view your subscriptions and choose to renew them.

**Additional context**
When testing we've seen the logout happen at different stages of the process (sometimes not until after the subscriptions page loads.

**Comment by castaway** [comment]
Fixed in today's update
