### ISSUE TITLE
Calendar events that are all day events are added across two days

### ISSUE THREAD

**Issue by runboxdave** [runbox/runbox7#1292]
**Describe the bug**
Calendar events that are annually recurring all day events are added across two days

**To Reproduce**
1. Add a new event
2. Set to all-day

Going back to the event the Details tab shows the all-day has  been turned off and times inserted instead.

**Expected behavior**
Event should be set correctly to the parameters set.

Might be related to https://github.com/runbox/runbox7/issues/745

**Comment by castaway** [comment]
.. and keeps being extended a day every time you edit it!

**Comment by castaway** [comment]
See also #1269
