### ISSUE TITLE
Username is cached after switching accounts

### ISSUE THREAD

**Issue by gtandersen** [runbox/runbox7#1295]
**Describe the bug**
When logging out of an account and into another account, the previous account's username is cached until a reload of the app is completed.

**To Reproduce**
1. Go to https://runbox.com/app and log into an account
2. Log out of the account and into another account
3. Observe that the first account's username is shown in the top left area
4. Reload the app and the username is updated to the current account

**Expected behavior**
The username should be displayed correctly.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Firefox

**Comment by piratefinn** [comment]
Unable to reproduce this on Chrome or Firefox on Win10, for myself it shows this as though the entry is blanked then a half second later loads the correct one in, as though it is not doing the caching of username in the same way at all.
![image](https://user-images.githubusercontent.com/5954123/194306271-011c1c4d-a94a-4f40-892c-2f73a87fffd4.png)

**Comment by castaway** [comment]
I think I fixed this one a while back (while doing some other work to ensure the user data got updated on change)
