### ISSUE TITLE
Thumbnails of attached images not loaded

### ISSUE THREAD

**Issue by kotecky** [runbox/runbox7#1303]
Thumbnails of attached images are not loaded. The server response seems OK but the image files are empty: 

![image](https://user-images.githubusercontent.com/2297444/188403859-d5c4e71a-e7b0-4701-a696-086056931d29.png)

![image](https://user-images.githubusercontent.com/2297444/188405052-294f6b5f-ab9a-4f6b-b3ee-c57d219b6e02.png)

This is despite the setting "show images" is set to Yes for the given sender (inline images display, their thumbnails do not).

**Comment by castaway** [comment]
Verified as an issue - could an issue in the REST api or the front end, handing to Finn

**Comment by gtandersen** [comment]
@piratefinn Does that indicate an issue with the file itself as downloaded, or that the file is not provided to the front-end?

**Comment by piratefinn** [comment]
> @piratefinn Does that indicate an issue with the file itself as downloaded, or that the file is not provided to the front-end?

The latter. The mix of behaviours is something I pin to Chrome Developer tools just being picky about what it can easily preview, but with how it behaved with jpeg's with it working when downloaded in preview but not with server, I'm going to assume the issue is with the REST API.

**Comment by castaway** [comment]
Ah darn, this is another instance of internal issue 1185 (should up the priority of that one!)

**Comment by kotecky** [comment]
Using [ Runbox 7 build time: 2023-03-29T09:47:33.942Z ] in FF under Win10 and Android8: yes, it still is there. One JPG, the other PNG: 
![image](https://user-images.githubusercontent.com/2297444/228563863-579246cc-2e26-40a8-a31e-7c745800e2c4.png)

**Comment by gtandersen** [comment]
Confirmed to not work in Firefox 111.0.1 on macOS.

**Comment by castaway** [comment]
Thanks, @kotecky I've now improved the fix (missed a step previously!), how's that looking now?

**Comment by kotecky** [comment]
@castaway Bingo, that's it!

Now if there was a way to skip the signature logos and give hints on the name and the type of the attachment (PDFs are clear, many others [doc, ods, xls, ..., ...] not): 

![image](https://user-images.githubusercontent.com/2297444/228821927-9e5cce8a-b48f-4601-b17c-ad5aa09bbe2a.png)

**Comment by castaway** [comment]
We have an issue for that: #1061 :)

**Comment by kotecky** [comment]
Besides that hovering could give the type, size, full name, option to open in a new tab or download (for images only?). There is plenty of space in the large preview squares. Which would be a different issue than #1061?

**Comment by gtandersen** [comment]
@kotecky Agreed; please feel free to open a new enhancement issue for showing additional file details. 

Note that file handling should be controlled by the browser as in https://github.com/runbox/runbox7/issues/79#issuecomment-1492641502.

**Comment by kotecky** [comment]
@gtandersen, done: #1446
