### ISSUE TITLE
HTTP failure response

### ISSUE THREAD

**Issue by kotecky** [runbox/runbox7#1309]
When clicking on some messages (but not on all) in the message list, the following error pops-up: 
![image](https://user-images.githubusercontent.com/2297444/189304816-9cf7c063-3f4a-4dab-97f6-1fff05c773d9.png)

Given that the pop-up appears immediately after clicking, it is unlikely that the timeout is a correct interpretation of what happens. 

In any case, the message should be displayed but never appears. Instead, the message pane gets closed. 

Latest FF, Win 10.

**Comment by gtandersen** [comment]
Thanks for the report @kotecky.

Does this error occur on the same message(s) or is it random in that regard? As you say it's unlikely an actual timeout if the error is displayed immediately.

**Comment by gtandersen** [comment]
See also #1065.

**Comment by kotecky** [comment]
@gtandersen I did not pay attention to this, will the next time.

**Comment by castaway** [comment]
We fetch messages in the background (when loading index and/or when switching/visiting folders) - so this is probably a case of the error-case being stored on that fetch. That definitely shouldn't be happening
