### ISSUE TITLE
Can't delete or move specific emails

### ISSUE THREAD

**Issue by MoritzLost** [runbox/runbox7#1311]
**Describe the bug**

I have three emails in my inbox that I can't delete or move to a different folder. Performing one of those actions will result in the email disappearing from my inbox temporarily, but reloading the tab or switching folders will cause them to reappear. The following error is logged to the console:

```
TypeError: can't access property "total", i.folderCounts[r.folder] is undefined
    moveMessages main.d401b495601564d1f2db.js:1
    moveMessages main.d401b495601564d1f2db.js:1
    updateLocal main.d401b495601564d1f2db.js:1
    updateMessages main.d401b495601564d1f2db.js:1
    deleteMessages main.d401b495601564d1f2db.js:1
    Io main.d401b495601564d1f2db.js:1
    Bo main.d401b495601564d1f2db.js:1
    r main.d401b495601564d1f2db.js:1
    E main.d401b495601564d1f2db.js:1
    i main.d401b495601564d1f2db.js:1
    invokeTask zone.js:421
    onInvokeTask main.d401b495601564d1f2db.js:1
    invokeTask zone.js:420
    runTask zone.js:188
    invokeTask zone.js:503
    y zone.js:1671
    g zone.js:1697
    D zone.js:1823
    scheduleTask zone.js:407
    onScheduleTask zone.js:294
    scheduleTask zone.js:400
    scheduleTask zone.js:231
    scheduleEventTask zone.js:257
    I zone.js:1980
    _wrapEventTarget main.d401b495601564d1f2db.js:1
    be main.d401b495601564d1f2db.js:1
    value main.d401b495601564d1f2db.js:1
    value main.d401b495601564d1f2db.js:1
    value main.d401b495601564d1f2db.js:1
    value main.d401b495601564d1f2db.js:1
    Yo main.d401b495601564d1f2db.js:1
    Uo main.d401b495601564d1f2db.js:1
    Io main.d401b495601564d1f2db.js:1
    na main.d401b495601564d1f2db.js:1
    $r main.d401b495601564d1f2db.js:1
    value main.d401b495601564d1f2db.js:1
    value main.d401b495601564d1f2db.js:1
    value main.d401b495601564d1f2db.js:1
    set main.d401b495601564d1f2db.js:1
    ja main.d401b495601564d1f2db.js:1
    la main.d401b495601564d1f2db.js:1
    Do main.d401b495601564d1f2db.js:1
    template main.d401b495601564d1f2db.js:1
    na main.d401b495601564d1f2db.js:1
    ea main.d401b495601564d1f2db.js:1
    Oa main.d401b495601564d1f2db.js:1
    ea main.d401b495601564d1f2db.js:1
    ea main.d401b495601564d1f2db.js:1
    ea main.d401b495601564d1f2db.js:1
    ea main.d401b495601564d1f2db.js:1
    Oa main.d401b495601564d1f2db.js:1
    ea main.d401b495601564d1f2db.js:1
    ea main.d401b495601564d1f2db.js:1
    ta main.d401b495601564d1f2db.js:1
    Ea main.d401b495601564d1f2db.js:1
    Ea main.d401b495601564d1f2db.js:1
    value main.d401b495601564d1f2db.js:1
    value main.d401b495601564d1f2db.js:1
    next main.d401b495601564d1f2db.js:1
    invoke zone.js:386
    onInvoke main.d401b495601564d1f2db.js:1
    invoke zone.js:385
    run zone.js:143
    value main.d401b495601564d1f2db.js:1
    next main.d401b495601564d1f2db.js:1
    o main.d401b495601564d1f2db.js:1
    value main.d401b495601564d1f2db.js:1
    value main.d401b495601564d1f2db.js:1
    value main.d401b495601564d1f2db.js:1
    value main.d401b495601564d1f2db.js:1
    value main.d401b495601564d1f2db.js:1
    value main.d401b495601564d1f2db.js:1
    hl main.d401b495601564d1f2db.js:1
    pl main.d401b495601564d1f2db.js:1
    onInvokeTask main.d401b495601564d1f2db.js:1
    invokeTask zone.js:420
    runTask zone.js:188
    invokeTask zone.js:503
    y zone.js:1671
    g zone.js:1697
    D zone.js:1823
    scheduleTask zone.js:407
    onScheduleTask zone.js:294
    scheduleTask zone.js:400
    scheduleTask zone.js:231
    scheduleEventTask zone.js:257
    I zone.js:1980
    _wrapEventTarget main.d401b495601564d1f2db.js:1
    be main.d401b495601564d1f2db.js:1
    value main.d401b495601564d1f2db.js:1
    value main.d401b495601564d1f2db.js:1
    value main.d401b495601564d1f2db.js:1
    value main.d401b495601564d1f2db.js:1
    Yo main.d401b495601564d1f2db.js:1
    Uo main.d401b495601564d1f2db.js:1
    g main.d401b495601564d1f2db.js:1
    na main.d401b495601564d1f2db.js:1
    $r main.d401b495601564d1f2db.js:1
    value main.d401b495601564d1f2db.js:1
    value main.d401b495601564d1f2db.js:1
    value main.d401b495601564d1f2db.js:1
    set main.d401b495601564d1f2db.js:1
    ja main.d401b495601564d1f2db.js:1
    la main.d401b495601564d1f2db.js:1
    Do main.d401b495601564d1f2db.js:1
    template main.d401b495601564d1f2db.js:1
    na main.d401b495601564d1f2db.js:1
    ea main.d401b495601564d1f2db.js:1
    Oa main.d401b495601564d1f2db.js:1
    ea main.d401b495601564d1f2db.js:1
```

**To Reproduce**

Click the checkbox next to the email in question and click the delete button, or the button to move it to a different folder and select the target folder. Doing the same thing from the header buttons in the email side panel yields the same result.

This only happens with three specific emails at this moment, not sure how to reproduce exactly. Synchronizing the account index didn't help.

**Expected behavior**

Deleting or moving emails should work correctly.

**Desktop**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 105

**Comment by castaway** [comment]
The error would seem to imply that the code/system doesn't have any folder count information for the folder you're moving the messages from, which sounds a bit odd. Which folder are they in? Is it a standard one, or one you created? Does the left folder list give message counts (total / read) for that folder?

I think the error you're seeing is from this line:
https://github.com/runbox/runbox7/blob/master/src/app/rmmapi/messagelist.service.ts#L352

**Comment by MoritzLost** [comment]
> Which folder are they in? Is it a standard one, or one you created?

It's the standard inbox folder. 

> Does the left folder list give message counts (total / read) for that folder?

The sidebar shows both the Inbox folder and the target folder with correct message counts.

---

The messages are now gone, as far as I can tell, so deleting them worked in the end. It was still a very persistent issue that existed across several restarts and full reloads, so it would still be worth looking into this.

**Comment by MoritzLost** [comment]
I'm having the same issue again. I want to delete two E-Mails in my Inbox that have been there a while, but can't. Selecting them from the list and then using the delete button makes them disappear from the list, but only temporarily - the same error quoted above is logged to the console, and the flyout menu (with the delete button) _doesn't_ disappear as it normally does. As soon as I click on another e-mail, the two e-mails I tried to delete appear in the list again. Trying to delete the mail from the preview pane does nothing, but triggers the same error mentioned above.

Any progress on fixing this issue? Not being able to delete e-mails is a really annoying bug and should be given high priority!

**Comment by gtandersen** [comment]
@MoritzLost Thanks for the update. 

We have confirmation of this occurring intermittently in other accounts as well and are investigating the issue.

**Comment by gtandersen** [comment]
@MoritzLost Other occurrences of this issue appear to have been related to moving/deleting messages from a search result. Can you confirm that the problem occurs when deleting from a folder message list and not a search result?

**Comment by MoritzLost** [comment]
> @MoritzLost Other occurrences of this issue appear to have been related to moving/deleting messages from a search result. Can you confirm that the problem occurs when deleting from a folder message list and not a search result?

@gtandersen Yes, in my case, I was trying to delete an email from the regular `Inbox` folder with no search applied.

I ended up moving / deleting the emails through the Gmail app, which worked fine. So it looks like it's indeed an error at the interface level, not in the server.

**Comment by castaway** [comment]
Updated a bunch of stuff related to working with folders (emptying trash, renaming etc) .. any improvement for this?

**Comment by MoritzLost** [comment]
@castaway Hard to say, I can't reliably reproduce this issue after all. The last time it happened, I deleted the affected emails through the Gmail app. I'll post here if I encounter this issue again!

**Comment by gtandersen** [comment]
@castaway This does seem to be more reliable currently.

**Comment by MoritzLost** [comment]
@castaway @gtandersen This issue is definitely still happening. Just got it with some new emails. Same behaviour and console error as before. Three emails were received around two weeks ago, sat unopened in my inbox for a while. Now I've read them and want to delete them, but I'm still getting this error.

One thing I noticed is that all three of those were originally sorted into a different folder based on my filters. I moved them to the inbox (to be read later). Not sure if this applied to the original emails I had this problem with as well, but I'd wager a guess this is related to trying to delete an email that was moved from another folder to the inbox.

**Comment by MoritzLost** [comment]
@castaway Seems like this was resolved? Anyway, in case it crops up again:

> Do you have the index syncing on or off?

On.

> When you move the message from the folder it was sorted into to the Inbox, do the folder counts update correctly? (which method do you use to move it?)

Not sure, folder counts are very inconsistent regardless of this error. Often the badge with unread messages only updates after a long delay when moving / deleting emails, and the folder count for larger folders seems to be unreliable as well.

> Same folder counts question for when you attempt to delete one.

Can't reproduce any more since I deleted those mails using Gmail.

**Comment by gtandersen** [comment]
@MoritzLost Thanks for the additional details. Please feel free to reopen the issue if the problem occurs again.
