### ISSUE TITLE
Changelog is not available

### ISSUE THREAD

**Issue by gtandersen** [runbox/runbox7#1318]
**Describe the bug**
The changelog is no longer available.

**To Reproduce**
1. Go to https://runbox.com/app/changelog
2. Observe that the browser redirects to https://runbox.com/app

**Expected behavior**
The changelog should be visible at the given URL.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Firefox

**Comment by castaway** [comment]
Probably because: ```
Uncaught (in promise): Error: Invalid change type "sstyle" in e7a2c18,1663354325,sstyle,payment,Clarify main accounts vs sub-accounts.
Error: Invalid change type "sstyle" in e7a2c18,1663354325,sstyle,payment,Clarify main accounts vs sub-accounts
```

**Comment by gtandersen** [comment]
@castaway Thanks -- for some reason it passed the policy test.

See https://github.com/runbox/runbox7/pull/1319 for corrected commit message.
