### ISSUE TITLE
Forwarding an HTML formatted message should default to HTML mode

### ISSUE THREAD

**Issue by castaway** [runbox/runbox7#1329]
**Describe the bug**
I clicked Forward on an HTML message with images in, the compose editor (as thats my default), displayed it in plain text mode. I expected to get HTML mode to match the message.

**To Reproduce**
1. Open an HTML formatted incoming message
2. Turn on "view HTML / show images" settings
3. Hit the "forward" button
4. Compose window displays the new message in plain text mode
5. Hit "HTML" - image displays messed up (this is in an issue elsewhere)

**Expected behavior**
Draft editing window is in HTML mode

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Gentoo Linux
 - Browser Vivaldi
 - Version 5.5

**Comment by castaway** [comment]
This seems to be working ok for me today (though I don't remember fixing it). Would appreciate re-testing by others @gtandersen , @runboxdave ?

**Comment by gtandersen** [comment]
This appears to be working correctly now; closing.
