### ISSUE TITLE
Menu not visible in Settings on mobile

### ISSUE THREAD

**Issue by gtandersen** [runbox/runbox7#1337]
**Describe the bug**
When going to Settings with a mobile device the top and side menus are hidden and can't be pulled out. 

**To Reproduce**
1. Go to https://runbox.com/app (or the PWA) with a mobile device (or Responsive Design Mode)
2. Click on Settings in the main menu
3. Observe that there are no menus, and no way to show the menus

**Expected behavior**
It should be possible to pull out the menu in order to navigate to other areas of the app, similar to Mail, Contacts, and Calendar.

**Screenshots**
<img width="372" alt="Account Settings mobile" src="https://user-images.githubusercontent.com/1620058/203836632-ec92f3c0-67b3-4270-a306-c376551650ea.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Firefox (Responsive Design Mode)

**Comment by castaway** [comment]
This seems to work ok for me now in current runbox.com (using chrome + firefox responsive mode)

**Comment by gtandersen** [comment]
Confirmed to work; closing issue.
