### ISSUE TITLE
Aliases screen

### ISSUE THREAD

**Issue by gtandersen** [runbox/runbox7#1350]
**Describe the solution you'd like**
Upgrade the Runbox 6 Account > Aliases screen (https://runbox.com/mail/account_alias) to Angular with existing functionality.

**Comment by castaway** [comment]
Aliases screen in Runbox7 should be part of: https://runbox.com/app/account/identities, aka src/app/profiles/profiles.component.ts

**Comment by gtandersen** [comment]
Although they overlap, aliases is for receiving email and identities for sending email, so they should remain on different screens.

**Comment by castaway** [comment]
Done
