### ISSUE TITLE
List of drafts changes completely after deletion of a draft

### ISSUE THREAD

**Issue by kotecky** [runbox/runbox7#1370]
**Describe the bug**
List of drafts changes completely after deletion of a draft. 

**To Reproduce**
1. Go to the Drafts folder. 
2. Click on a draft to start editing. 
3. Click on the Delete icon. 
4. See error: the list shows old drafts, not the most recent ones. 
5. (Stop and restart of synchronization does not change the behaviour. Stop sync, logout, delete app data and cache from browser, login, start sync does not help either.)

**Expected behavior**
Drafts listed ordered by the last-edited date. 

**Desktop (please complete the following information):**
 - OS: Win10
 - FF
 - latest

**Screenshots**

Before deleting the first draft: 
![image](https://user-images.githubusercontent.com/2297444/214264572-62e64a9d-2d50-465b-b9ab-1c9b3d57c8ff.png)

After deleting the first draft: 
![image](https://user-images.githubusercontent.com/2297444/214264599-567be955-b7b0-4eb5-b929-44046f46ac0b.png)

**Comment by gtandersen** [comment]
@kotecky Thanks for the bug report. We have since made improvements to the Draft Desk and can't currently reproduce this issue.

Please reopen if this still occurring for you.
