### ISSUE TITLE
Prevent simultaneous index downloads

### ISSUE THREAD

**Issue by gtandersen** [runbox/runbox7#1378]
**Describe the bug**
In certain circumstances (possibly low bandwidth situations) multiple concurrent index downloads can be observed when inspecting Network traffic in the browser.

**To Reproduce**
1. Go to https://runbox.com/app while using a low bandwidth connection, and ensure local index is enabled
2. Observe the network traffic in the browser's Dev Tools

**Expected behavior**
Only one index update should be downloaded at a time, such that the next download is postponed until the current one is completed.

**Screenshots**
<img width="893" alt="Safari network activity" src="https://user-images.githubusercontent.com/1620058/216969638-564453ff-bd67-4698-8d4f-efd5506d9f1c.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Safari

**Comment by castaway** [comment]
In chome on a long running tab, I can see that most of these "download_xapian_index" calls are actually "refresh drafts folder" ones (folder=Drafts query param), and those are increasing.  I will fix that issue first, as it doesnt seem like the "normal" index fetch (for all changes) is happening any more often / overlapping than it should
