### ISSUE TITLE
#Payments: Stripe payments hang when users attempt to reopen status 4 accounts

### ISSUE THREAD

**Issue by perigrin** [runbox/runbox7#1409]
https://gitlab.runbox.com/runbox/payment/-/issues/23

**Comment by castaway** [comment]
Tested together with @runboxdave - we can't reproduce this with manual testing (setting an account to status=4 deliberately). However we discovered a related issue, created as #1554

**Comment by gtandersen** [comment]
Closing issue since it isn't reproducible.
