### ISSUE TITLE
Show popup with URL when hovering over links in messages

### ISSUE THREAD

**Issue by gtandersen** [runbox/runbox7#1425]
**Is your feature request related to a problem? Please describe.**
When an HTML message contains a link it can be difficult for the user to see where the link will actually take them, unless they are used to checking the browser's status bar while hovering over the link.

The ability to inspect URLs is crucial in order to detect possible phishing, so we should make it easier to see the actual URL.

**Describe the solution you'd like**
Show a pop-up showing the real URL when hovering over links in messages.

**Comment by castaway** [comment]
Backend MR submitted
