### ISSUE TITLE
Make payment page more dynamic regarding suitable add-ons

### ISSUE THREAD

**Issue by gtandersen** [runbox/runbox7#1433]
**Is your feature request related to a problem? Please describe.**
It can be difficult to choose the most suitable subscription plan on the payment page.

**Describe the solution you'd like**

<s>1. Suggest the correct number of sub-accounts according to the number of trial accounts the user has set up. (Deprecated)</s>
<s>2. Don't show plans without Email Hosting support for Email Hosting accounts. (Deprecated)</s>
3. Prevent renewals of add-ons that are not allowed with the current subscriptions, e.g. more than 1 Email Hosting domain with Micro accounts.
4. Highlight subscription plan upgrades when an account is close to storage or other quotas.
5. When a customer completes a payment and clicks "Close" on the payment dialogue it might be more useful to take them to the subscriptions page to see their purchases rather than show them an empty basket with a sad face. :)
6. Convert the "card" layout to a table where it's easier to compare plans and especially distinguish between main and sub-accounts.
7. Bonus item: Add company information such as address and business registry ID.

**Comment by castaway** [comment]
nr 3 can be done with #1014 , we just need to specify what "close to" means, what's the tolerance for the highlight?

**Comment by gtandersen** [comment]
> nr 4 can be done with #1014 , we just need to specify what "close to" means, what's the tolerance for the highlight?

90% is a good threshold in general (also used for email alerts about disk space vs quota).

**Comment by castaway** [comment]
Upgrades page improvements:



![Image](https://github.com/runbox/runbox7/assets/109990/b734c912-2f86-4c4f-90ca-9dcaa3b99ac9)
![Image](https://github.com/runbox/runbox7/assets/109990/4867b97d-5f8c-4497-a161-26b6c2761e45)
