### ISSUE TITLE
#Composse: Composing a draft displaces the message within the "draft desk" after few seconds

### ISSUE THREAD

**Issue by kotecky** [runbox/runbox7#1562]
**Describe the bug**
When i start writing a new message, it is opened on the top of the Draft Desk to start with. After a short moment, the message is reordered to the end of the Draft desk. Which actually means that most of the message disappears below the lower edge of the window. This is annoying because loosing focus on what and where i do. 

**To Reproduce**
1. Click on Compose
2. Start writing
3. Message changes it's place among the other saved drafts

**Expected behavior**
Keep the place of the current draft in place. 
Probably a different issue but may be the solution: The draft messages should be ordered newest-to-oldest. No idea why it recently changed. 

**Desktop (please complete the following information):**
 - OS: Win 10
 - FF
 - 125.1

**Comment by gtandersen** [comment]
@kotecky Thanks for this report -- confirmed to be a problem and we are looking into it right away.
