### ISSUE TITLE
Message search with server index does not show unread messages in bold

### ISSUE THREAD

**Issue by runboxdave** [runbox/runbox7#192]
Unread messages are shown the same as other messages rather than in bold. This is different behaviour to that which we previously had in RMM6, but of course both interfaces are affected now.

**Comment by petersalomonsen** [comment]
This is only when using server side search? Using local search index should differentiate with bold/normal on unread/read messages.

**Comment by davidbowdley** [comment]
That could be the case for this particular customer.

**Comment by gtandersen** [comment]
Is this still an issue @runboxdave?

**Comment by gtandersen** [comment]
This is no longer reproducible; closing issue.
