### ISSUE TITLE
README clarification

### ISSUE THREAD

**Issue by ng-0** [runbox/runbox7#197]
In the README your write:

> Development with your own Runbox server installation
>
> Run npm run appdev and you will be able to access Runbox 7 at https://yourvm/appdev

However this seems to be limited by scope to the developers working at Runbox as the backend is only described roughly by technology stack (Perl5, MySQL) but no detailed description is given.
I can understand this for maybe security reasons, maybe competition reasons, maybe time to document reasons, maybe all of it or none of those reasons.

So far new developers will only be able to contribute if they have an runbox account for testing or manage to replicate an compatible backend, as far as my reading goes.

I'm time constrained but would like to dive more into contributing and taking on tickets. Having the ability to test with a subset of what you run in production, even if it isn't close to it, might increase the likelihood of more contributions.

**Comment by gtandersen** [comment]
Hi @ng-0 and thanks for your message.

We're aiming to open source the Runbox 7 backend in the future, but it is a bigger project that will take time.

In the meantime, we're happy to provide you (and others) with a Runbox account for testing and development at https://runbox.com.

Just set up a trial account and then contact Runbox Support (https://support.runbox.com) with a reference to this issue, and we'll take care of it.

**Comment by ng-0** [comment]
Hi,

thanks for your reply.

Interesting to read, and understandable.

I was generally speaking - I think having a customer account as I do, on and off since early '00s, is a precondition I have fulfilled if I understand you correctly.

Regardless of this, the README should probably reflect this for more direct exposure.

**Comment by gtandersen** [comment]
@ng-0 Thanks for the suggestion, which has resulted in these changes to the README: https://github.com/runbox/runbox7/pull/210/files

Thank you as well for being a long-time Runbox user -- we're looking forward to any contributions you'd like to make, in which case the offer above still stands. :)

**Comment by ng-0** [comment]
Thanks.

Looks good to me. Would've been good to mention that the backend might see a release, but maybe it's better to not mention it while it's not an active project.

I'm closing this ticket since it's done.
