### ISSUE TITLE
"Undefined" ipo header when replying

### ISSUE THREAD

**Issue by kotecky** [runbox/runbox7#234]
When replying to a message, the word "undefined" is placed in place of the "reply header" (from, time, to, subject). Spotted once, could not reproduce even with the same message, message being replied-to has all fields (from and to email, subject not blank).

> ![image](https://user-images.githubusercontent.com/2297444/63085849-ce3d7800-bf4e-11e9-940c-1726d9311e6d.png)

**Comment by gtandersen** [comment]
Not able to reproduce this. Closing issue; reopen if it occurs again.

**Comment by kotecky** [comment]
Since recently i get it every time, irrespective of the sender's client (desktop, phone app, automated email). HTML email seems to be a precondition. 

( Runbox 7 build time: 2021-11-15T13:08:33.650Z )

**Comment by gtandersen** [comment]
Yes, I see this too now on HTML messages.

@kvviecien Could this be related to https://github.com/runbox/runbox7/pull/1120, or is it independent?

**Comment by kvviecien** [comment]
@gtandersen There is a possibility my fix could break after fixing the headers for recent Sentry issues, because that's the same part of the code. I will look into it again.

**Comment by gtandersen** [comment]
This appears to be much better but can still be reproduced with some messages, e.g. with https://runbox.com/app/#Inbox:12205016 in the test account.

**Comment by kotecky** [comment]
Still there, confirmed.

**Comment by kotecky** [comment]
Is it not persistent when answering to more than one recipient?

**Comment by gtandersen** [comment]
@kotecky Thanks for the updates. 

Do you mean that the error occurs when replying to one recipient but not when replying to more than one recipient?

**Comment by kotecky** [comment]
@gtandersen, that's what I meant, but dud not try. A hypothesis to be tested.

**Comment by gtandersen** [comment]
Not reproducible with the above example message.

Closing issue; reopen if it occurs again.

**Comment by kotecky** [comment]
@gtandersen To be reopened as it is currently happening again.

**Comment by kotecky** [comment]
> @gtandersen To be reopened as it is currently happening again.
@gtandersen Issue still there.

**Comment by gtandersen** [comment]
@kotecky Issue reopened.

Would you be able to provide an example message (your Runbox username and the message's ID from the browser URL) via Runbox Support?

Thanks!

**Comment by kotecky** [comment]
@gtandersen 
Answering to the support via a ticket.

**Comment by kotecky** [comment]
But i have the impression that it has to do with the state (slow XRH or something) rather than the message itself - sometimes it kicks in ("undefined") for one message but not when trying the second time for the same message. A third attempt would be again "successful" in reproducing.

**Comment by gtandersen** [comment]
@kotecky Thanks for the additional details. This then appears to be performance related and not caused by a bug per se.
