### ISSUE TITLE
"Reply header" missing separators or spaces

### ISSUE THREAD

**Issue by kotecky** [runbox/runbox7#235]
The "reply header" (from, date, to, subject) displayed on top of the text of the message being replied to, misses separators or spaces. Example: 

`From: Info <info@abc.org>Time:2019-08-14 11:24To: Peter <peter@abc.org>RE: topics`

**Comment by gtandersen** [comment]
Reproducible in HTML messages.

**Comment by kotecky** [comment]
Still there...

Some of the words are not needed. The _subject_ is a repeat from the header of the of the reply, the _to_ is quite often me. 
Thunderbird handles the header efficiently: 
`On 2021-02-15 v 15:01, Peter Pan wrote:`
Would it be a sensible alternative? If the _to_ field is needed, would this be better?
`On 2021-02-15 v 15:01, Peter Pan wrote to Some Name:`

**Comment by gtandersen** [comment]
Agreed, either of those are better options.
