### ISSUE TITLE
Calendar: hints

### ISSUE THREAD

**Issue by kotecky** [runbox/runbox7#240]
When clicking on calendars in the calendar list there are two hidden actions that i was searching for (and found the second only after a minute by stubborn searching): edit calendar properties and show/hide calendar. 

The presence of both actions should be made clear by a title appearing on hover.

**Comment by tadzik** [comment]
PR is up: https://github.com/runbox/runbox7/pull/250

**Comment by tadzik** [comment]
This has been merged and is live now :)
