### ISSUE TITLE
Calendar: add event window

### ISSUE THREAD

**Issue by kotecky** [runbox/runbox7#241]
The size of the "add event" window is not responsive to the size of the device screen. Example from a laptop: 

![image](https://user-images.githubusercontent.com/2297444/63089069-faf58d80-bf56-11e9-8deb-179d1fadd937.png)

Should be somewhat bigger on a large screen and should fill (nearly or completely) a mobile phone screen.

**Comment by gtandersen** [comment]
This has been fixed.
