### ISSUE TITLE
Inbox: read messages not hidden when requested

### ISSUE THREAD

**Issue by kotecky** [runbox/runbox7#246]
In inbox after checking the checkbox "unread only", several unread images disappear but far from all. Approx ~ 70% remain.

**Comment by tadzik** [comment]
Sorry for the late reply; does it help if you remove the local index ("Stop index synchronization") and download it again? It sounds like something went wrong with it. Is it still happening today?

**Comment by kotecky** [comment]
I don't reproduce the issue any more.
