### ISSUE TITLE
calendar: short 'meetings' collapsed

### ISSUE THREAD

**Issue by kotecky** [runbox/runbox7#252]
In calendar when a meeting is too short (in the rb7 screenshot 0, 5 and 15 minutes), the meeting is collapsed: 
![zero minutes meeting - runbox7](https://user-images.githubusercontent.com/2297444/63423216-199ecd00-c40c-11e9-9424-5ff1aa9efc0a.png)
This is how outlook deals with short meetings: 
![zero minutes meeting - outlook](https://user-images.githubusercontent.com/2297444/63423255-291e1600-c40c-11e9-9f3d-84858c63f8ff.png)
Imho it should be improved for readability.

**Comment by tadzik** [comment]
(Should possibly be fixed upstream in angular-calendar)

**Comment by tadzik** [comment]
Reported upstream: https://github.com/mattlewis92/angular-calendar/issues/1192
