### ISSUE TITLE
Keep open/closed state of folder pane when clicking on Compose or Drafts

### ISSUE THREAD

**Issue by kotecky** [runbox/runbox7#266]
When clicking on Drafts, the folders pane closes and reopens. It should be kept closed when closed, or open when open.

**Comment by kotecky** [comment]
Same/similar behavior observed after sending a message: inbox opens with folder pane closed, folder pane opens immediately after inbox displays.

**Comment by gtandersen** [comment]
This behavior also occurs when clicking Compose, Reply, and Forward.

**Comment by gtandersen** [comment]
This is fixed and can no longer be reproduced. Reopen if this is not the case.
