### ISSUE TITLE
Text overflows message box in Drafts view, Firefox Quantum 69

### ISSUE THREAD

**Issue by deutrino** [runbox/runbox7#297]
See attached. This is true for all messages with lots of copy when I scroll down. Also, all formatting is stripped and everything is smashed into a giant blog of text in long drafts.

![image](https://user-images.githubusercontent.com/304300/64924745-acd1e500-d7b5-11e9-9e5e-15418dcec3c8.png)

**Comment by deutrino** [comment]
Duplicate of #267 - whoops.

**Comment by gtandersen** [comment]
Thanks for the bug report -- and for noticing it was a duplicate. :)
