### ISSUE TITLE
checkboxes toggled in folder with message open are cleared upon message close

### ISSUE THREAD

**Issue by deutrino** [runbox/runbox7#303]
STEPS TO REPRODUCE

1. Open a folder.
1. Open a message.
1. Toggle some checkboxes in the folder with the message open.
1. Close the message.

EXPECTED RESULT

The checkboxes' toggle state is not changed.

ACTUAL RESULT

The toggled checkboxes are cleared.

**Comment by gtandersen** [comment]
@deutrino This seems to be a duplicate of #10.

**Comment by tadzik** [comment]
Somewhat related to https://github.com/runbox/runbox7/issues/542.

**Comment by vertigo220** [comment]
Agree this is a duplicate of #10.

**Comment by gtandersen** [comment]
This is no longer reproducible; closing issue.
