### ISSUE TITLE
Provide an option for HTML without images

### ISSUE THREAD

**Issue by runboxdave** [runbox/runbox7#31]
There appears to be no option to show HTML formatted emails without images. Without this option you have to use either HTML with images (which may be undesirable) or the plain text version of a message if it exists. 

The plain text version of a message intended to be see in HTML where possible can be difficult to navigate as the text will contain multiple image links making the actual message text difficult to read.

**Comment by gtandersen** [comment]
This could be extended to include all external sources, and then adding a pair of options to the HTML Options menu item:

- Toggle external sources
- Always show external sources

**Comment by castaway** [comment]
Defang, which I was looking at for the backend, seems to remove "@import" statements by default (which would remove the font include lines).

As for images, current thought is to have the backend produce both an HTML copy with images removed/replaced (as v6 does), and another without - then have the frontend decide which to display.
