### ISSUE TITLE
Don't include nickname in sent email

### ISSUE THREAD

**Issue by gtandersen** [runbox/runbox7#313]
When an address is selected from Contacts in Compose it's shown on the format Nickname <name@domain.tld>, which is also used in the outgoing email.

Instead of the Nickname, the First name and Last name should be used (when available).

**Comment by tadzik** [comment]
I tried it just now on my temporary friend, First „Nick” Last and it seems to be working as expected for me, though it's using all three parts:

![2019-10-31-165324_349x65_scrot](https://user-images.githubusercontent.com/86378/67963484-f740e100-fbfe-11e9-88ee-f64d6174dc58.png)

Do you think we should consider the nickname to be something "internal" that we don't send out?

**Comment by gtandersen** [comment]
Correct -- the nickname is for internal use only and should not be included in the sent message. 

The First and Last name should be used when available.

**Comment by tadzik** [comment]
Will be fixed in https://github.com/runbox/runbox7/pull/461 :)
