### ISSUE TITLE
Close/remove button on email address not available on small screens

### ISSUE THREAD

**Issue by kotecky** [runbox/runbox7#315]
When composing a message (new, re, fwd) the cross button is not visible on small screens for medium long or longer email addresses, works for shorter ones. My environment: FF on Android with a 720x1280 pixels screen.

Replicated on a laptop FF using ctrl+shift+M, resizing the screen let the buttons progressively disappear: 

![image](https://user-images.githubusercontent.com/2297444/65815094-dc87e080-e1ea-11e9-928d-f2c82a98b49b.png)

This might be addressed in conjunction with one of the related issues (https://github.com/runbox/runbox7/issues/237, https://github.com/runbox/runbox7/issues/300). Overlaying a semi-transparent button instead of forcing the email to break on several lines would be preferable.

**Comment by gtandersen** [comment]
This is currently not reproducible; closing issue.
