### ISSUE TITLE
Add more recurring event options

### ISSUE THREAD

**Issue by davidbowdley** [runbox/runbox7#331]
Add more complex recurring options such as:

- [x] First day of the month.

- [ ] Second Wednesday of the month.

- [ ] Every other week/month.

- [ ] Weekly/monthly with ability to select more than one day of a week.

And other possibly combinations...

**Comment by tadzik** [comment]
I think that "first day of the month" is actually covered if you create an event on the 1st and set it to recurring monthly. Is it currently not working as it should?

**Comment by davidbowdley** [comment]
OK. Ticket that off for you now (of course that works, I am sure I was thinking of first something else probably).

**Comment by castaway** [comment]
See recurrence notes on the RunboxCalendar page of our internal wiki.
