### ISSUE TITLE
Calendar: "...and 2 other events"

### ISSUE THREAD

**Issue by kotecky** [runbox/runbox7#366]
When there are more than 4 events for a date, the last two are replaced by a link/button "...and 2 other events". On click (so as on click on area of a day), a black line with all events for that day is displayed. 

Neither of the two (button/link or area) works when the day belongs to the next month. One needs to switch to the next month, then click. I consider this as a bug, can't find a reason for clicking so many times.

**Comment by tadzik** [comment]
Good news :) This was fixed ([here](https://github.com/runbox/runbox7/commit/e8c518a664dc12c73c675400b87e1781825d9be6)) with a bunch of other calendar improvements, mostly for mobile, and is due for release shortly :)

**Comment by kotecky** [comment]
Thanks!
