### ISSUE TITLE
Calendar description character(s?) lead to error

### ISSUE THREAD

**Issue by kotecky** [runbox/runbox7#367]
A character [ ’ ] causes an error when inserting or updating a calendar event. This being a very frequent character in many languages, it needs to be allowed to pass.

**Comment by tadzik** [comment]
Indeed. `'` is okay, but the proper `’` is not. Thanks for pointing it out, I'll take a look.

**Comment by tadzik** [comment]
The fix was required on the backend and is now in the pipeline for release soon(ish).

**Comment by tadzik** [comment]
Should work now. Please reopen if you can find a way to break it still :)
