### ISSUE TITLE
Reply and reply-all buttons inactive

### ISSUE THREAD

**Issue by kotecky** [runbox/runbox7#392]
With the new build (Dec 2) reply and reply-all buttons on top of the message pane stopped working. The forward button works. (FF on Win10)

**Comment by tadzik** [comment]
Hey,
I can't seem to reproduce this – works just fine for me.

Can you open the browser console (right click, Inspect Element, Console) and see if it throws out some errors when you click these buttons?

**Comment by kotecky** [comment]
Hi @tadzik, 

For runbox I use standard FF window: 
![image](https://user-images.githubusercontent.com/2297444/70032570-fc9e9c00-15ad-11ea-8a47-f88d19497c7e.png)

In a private browsing window (no cache): 
![image](https://user-images.githubusercontent.com/2297444/70032357-9dd92280-15ad-11ea-9944-ede340c33c03.png)

But now i do not reproduce it either. Nonetheless, it occurred several times yesterday already.

**Comment by kotecky** [comment]
@tadzik, this should be it: 

![image](https://user-images.githubusercontent.com/2297444/70048029-9d4e8500-15c9-11ea-8976-fea169d3e57f.png)

Could it be because i ran the /app-beta/ before?

**Comment by tadzik** [comment]
@kotecky can you confirm if it's only a problem for messages that don't have a `To` set?

**Comment by kotecky** [comment]
Yes, it's the case, my address is in CC, there is no TO.

**Comment by tadzik** [comment]
It's fixed in https://github.com/runbox/runbox7/pull/472 and should work live somewhen this week :)
