### ISSUE TITLE
#Feature-Add: Templates do not open in compose window

### ISSUE THREAD

**Issue by runboxdave** [runbox/runbox7#402]
Unlike in Runbox 6, when you click on a message in the Templates folder in Runbox 7 it doesn't open in the compose window and there appears to be no way to make this happen.

I would suggest a two step process as you really need a way to view the message to check it is the one you want to use, and then open it in compose.

**Comment by gtandersen** [comment]
The Templates folder should generally work like Drafts, except that templates should not be deleted after sending the message.

**Comment by gtandersen** [comment]
See also internal issue 946.
