### ISSUE TITLE
Remember message list display settings

### ISSUE THREAD

**Issue by gtandersen** [runbox/runbox7#41]
When refreshing the app or logging out and in again, remember the message list display settings such as "Conversation view".

**Comment by vertigo220** [comment]
The sizes of the panes are also reset. Interestingly, the sizes of the message list columns are not reset.

**Comment by castaway** [comment]
Currently seems to be no storage of the view settings at all - so even switching to Contacts then back to Webmail, has lost the setting. I'll add localStorage saving.
