### ISSUE TITLE
Change "Account Upgrades" to "Main Account Subscriptions"

### ISSUE THREAD

**Issue by davidbowdley** [runbox/runbox7#423]
In the payment cart system, rename "Account upgrades" to "Main account subscriptions". There is confusion here given that the title is not clear about what those product apply to without studying the details text. It also the place to go if you want to change your Main account plan to something that may not be an upgrade. It's potentially the cause of a number of purchase errors.

**Comment by gtandersen** [comment]
This is being discussed more generally in #424.
