### ISSUE TITLE
Sub-accounts no longer listed next to sub-account products

### ISSUE THREAD

**Issue by davidbowdley** [runbox/runbox7#425]
This relates to the listing of current/active products in Runbox 7.

In Runbox 6 it was possible to see a pop-up list of sub-accounts that are associated with a sub-account product. This was useful so customers could check the product they were going to renew was the one they intended to renew.

This isn't possible in Runbox 7 and would be incredibly useful.

**Comment by tadzik** [comment]
That'd make a bit confusing since https://runbox.com/app/account/components and its menu item is already called “Account Products”. We could rename it to “Account Components”, since that's how we refer to it in the code.
