### ISSUE TITLE
Incorrect display of accented letters in profile/identity name

### ISSUE THREAD

**Issue by kotecky** [runbox/runbox7#427]
My name is correctly spelled in the settings (here https://runbox.com/mail/account or here https://runbox.com/app/identities). Despite that, the accented characters appear scrambled in the list of sent emails and also to those, who receive the email.

**Comment by gtandersen** [comment]
Thanks for reporting this issue @kotecky. Would you mind posting a screenshot (anonymized) to illustrated the issue?

**Comment by kotecky** [comment]
When composing ( https://runbox.com/app/compose?new=true ), there is a dropdown with 7 lines (why do many? i'll ask in the forum): 
![image](https://user-images.githubusercontent.com/2297444/72662074-93021200-39e2-11ea-9ec3-5a9b84a12692.png)

In the account administration (styled rb6, https://runbox.com/mail/account ), section Personal Details: first name and last name are correctly spelled. 

In the admin section dedicated to setup identities and aliases (styled rb7, https://runbox.com/app/identities ) there are : 
* main identity (spelled correctly)
* two aliases (spelled correctly)
* two "other identities" (spelled correctly)

Let me know in case more is needed.

**Comment by gtandersen** [comment]
Thanks for the screenshot @kotecky. 

If I understand it correctly, the first (main) identity in the Compose drop-down is shown incorrectly?

**Comment by kotecky** [comment]
@gtandersen, in total, there are 7 lines: the first (reflecting one main identity, two aliases and two emails). 

**Dropdown:**
- my alias, wrong spelling
- my alias (the same, repeated), correct spelling
- "other identity" (rbox.com) (spelling? no accented characters)
- phone number alias (correct spelling)
- my alias identity (correct spelling)
- my alias identity (wrong spelling)
- phone number alias (wrong spelling)

Notes on the dropdown: 
- "my alias identity" is only one, repeated. For some reason it is defined in the Identities tab as 'email' and again as 'alias'.)
- The main identity (name.surname@runbox.com) is not present in the dropdown menu.
- The identities/aliases are repeated in the dropdown. No idea why. 

**In the identities:** 
- main identity (name.surname@runbox.com)
- two aliases (phone number alias, my identity)
- two emails (rbox.com, my identity)

The identities can't be updated in rb7 for the moment (BTW, when I edit the signature in the rb6, no effect, it stays) so no testing possible.

**Comment by hernan604** [comment]
Seems there are wrong and good characters in the same list.
Probably means one of the inputs created wrong characters. Maybe the imported ones or maybe the newer ones. 
Will check whats the problem here
