### ISSUE TITLE
No warning if not subscribed or the alternative email is not validated

### ISSUE THREAD

**Issue by aijony** [runbox/runbox7#428]
Runbox 6 gave me an error when I tried to send an email for a trial account that isn't validated. Runbox 7 let me send the message with no warning. After verifying the email, future messages obviously went through, but the old ones remained unsent.
I've subscribed regardless, but it made it confusing when testing the account.

**Comment by gtandersen** [comment]
Thanks for reporting this issue @aijony. We will fix it as soon as time allows.

**Comment by tadzik** [comment]
Thanks @aijony. This will be fixed in the next release.
