### ISSUE TITLE
Cannot reply to message with empty Subject or To field

### ISSUE THREAD

**Issue by gtandersen** [runbox/runbox7#43]
When attempting to reply to a message with an empty Subject or To field, nothing happens. Forward works with an empty Subject field, but not To field.

Ref: https://community.runbox.com/t/cannot-reply-reply-all-or-forward-when-ny-email-is-on-cc-or-bcc-and-to-is-empty/937

**Comment by castaway** [comment]
Testing the current state of this (I assume fixes have happened in the meantime):

* I can reply to a message with no Subject (and sent as CC)
* I can reply to a message with no Subject (even if CC and no TO)
* I can forward a message with no Subject (and sent as CC)

Can't forward the message with no Subject (CC and no TO) though, so I'll poke at that..
