### ISSUE TITLE
Edit identities form does not appear

### ISSUE THREAD

**Issue by kotecky** [runbox/runbox7#432]
With the last build (i do not know how was it before) the form to edit identities (https://runbox.com/app/identities, alias > edit) does not show up, only a small portion of the modal popup does. Tested in FF and Chrome.

**Comment by davidbowdley** [comment]
I see the same problem here. Only a thin vertical strip appears on the left side of the browser windows and nothing more.

**Comment by hernan604** [comment]
Fixed in latest commits. will go live on next delivery
