### ISSUE TITLE
Prevent setting up an identity if the alias doesn't exist.

### ISSUE THREAD

**Issue by runboxdave** [runbox/runbox7#443]
An identity can be created under "Other Identities" where an alias on our domain or the customer's own domain doesn't exist. It would be helpful to prevent this and tell the customer that the address should be set up in the alias section instead.

**Comment by davidbowdley** [comment]
I think this is the correct logic for this issue.
![add-identity](https://user-images.githubusercontent.com/5822260/85293527-640e3180-b495-11ea-8f35-b9c8221d2fb9.png)

**Comment by davidbowdley** [comment]
When I try to add an address that isn't on a Runbox hosted domain, or is on a customer domain on another Runbox account (the latter may not be relevant), I get the error "Could not load profiles".

**Comment by hernan604** [comment]
Could you re-test? 

I just tested and seems to work correctly. I was able to create a new identity for a random email/domain. And it displays the message "Email not validated".

So closing for now.
