### ISSUE TITLE
Cannot use identities, validation link doesn't work

### ISSUE THREAD

**Issue by compilin** [runbox/runbox7#445]
Hello,

I've tried adding a few identities, but I could not validate the addresses. The validation links I received open the webmail preference page where I get a "Error: The address could not be validated" message on a red band at the top of the page.

Trying to use the "re-send" feature on the identities page pops up a toast saying "Could not resend validation email". Additionally this logs an error in the console:

    Http failure response for https://runbox.com/rest/v1/profile/*****/resend_validation_email: 404 Not Found

(With the asterisks being what I assume to be the identity ID)

Additional info:
I'm using Chrome 78 on Debian 10.
I don't have any alias set up, I'm using domains with catch-all, but I also tried setting up a matching alias and it did not change the behaviour.
I have an accented character in my name which gets mis-encoded in all the emails I've received from Runbox, an encoding error I've seen enough (`é` -> `Ã©`) to know is caused by some UTF-8-encoded text decoded as ISO8859-1/Windows-1252. It's probably unrelated but I could see that causing the above issue, although the error still occurs if there is no accent in the identities's "From name" nor "Description".

**Comment by gtandersen** [comment]
Thanks for reporting this issue @compilin -- we will look into it.

**Comment by castaway** [comment]
This seems to currently work for me (Vivaldi, Gentoo), the resend link doesn't 404, and adding+validating a new one works fine.

Could you re-try please @compilin ?

**Comment by hernan604** [comment]
Has been fixed in the past so closing this issue
