### ISSUE TITLE
TinyMCE in HTML mode prevents the browser spellchecker working

### ISSUE THREAD

**Issue by davidbowdley** [runbox/runbox7#481]
When composing a message a browser's built in dictionary/spell checking doesn't work in HTML mode.

**Comment by gtandersen** [comment]
@davidbowdley This appears to have been solved via #622 -- or is it still occurring?

**Comment by davidbowdley** [comment]
We made a change to this so that the right-click works. However, it turned out there is a keyboard short cut users can use to disable the hijacking anyway on a click by click basis so if we ever needed to have TinyMCE right click options back we could and just let people know how to bypass that when they need the spell checker.

**Comment by gtandersen** [comment]
I can't reproduce this in Firefox or Chrome -- which browser is this occurring in?

**Comment by davidbowdley** [comment]
> I can't reproduce this in Firefox or Chrome -- which browser is this occurring in?

I'm not sure if you saw my comment above when I closed the issue. The issue of not being able to use the spell checker was resolved by disabling how TinyMCE used to hijack the right-click to present it's own options rather than the usual browser ones which included the spell checking options.

**Comment by gtandersen** [comment]
> > I can't reproduce this in Firefox or Chrome -- which browser is this occurring in?
> 
> I'm not sure if you saw my comment above when I closed the issue. The issue of not being able to use the spell checker was resolved by disabling how TinyMCE used to hijack the right-click to present it's own options rather than the usual browser ones which included the spell checking options.

Yes -- I was asking about it occurring when the hijacking is not disabled in the browser by the user.

**Comment by davidbowdley** [comment]
It's not disabled in the browser, it was disabled by us in TinyMCE. The user action I was referring to works if we don't disable this feature. We discovered the browser right click menu can still be accessed by holding down a key on the keyboard at the same time (it's one of control, option/alt or command but I don't recall which one).

**Comment by gtandersen** [comment]
Ok, I see now that the two things were separate and in addition to each other.

Keeping the issue closed.
