### ISSUE TITLE
Cancel button to interrupt upload of an attachment

### ISSUE THREAD

**Issue by kotecky** [runbox/runbox7#485]
It occurs that one decides to remove an attachment. For a large attachment or on a slow network it may take quite some time before the attachment uploads and the delete button becomes available. For the duration before that time a button interrupting the upload could be made available.

**Comment by kotecky** [comment]
Tanks for this, i just cancelled the attachment process of one: a file attached by mistake - same name, different extension, 100x different size ;)

**Comment by tadzik** [comment]
Thank you! I'm happy to see it was useful to you already :)
