### ISSUE TITLE
UI for replying to e-mails is wonky and unusable

### ISSUE THREAD

**Issue by billmcc64** [runbox/runbox7#498]
See the attached screenshot.   When I reply to an e-mail on this screen, everything looks ok until I start typing.

Once I hit return on the first line, the window scrolls down and hides the text that I am typing.   I scroll up and type another line and it does the same thing.    This is very hard to use.

This only occurs with HTML e-mail.    With plain text e-mail the window scrolls correctly.

![runbox-screenshot-2](https://user-images.githubusercontent.com/10180912/77487931-281dee80-6e0a-11ea-9b4c-c220626130e0.png)

The browser is Brave
Version 1.5.115 Chromium: 80.0.3987.149 (Official Build) (64-bit)

**Comment by gtandersen** [comment]
I am not able to reproduce this currently in Brave on macOS.

**Comment by billmcc64** [comment]
Well it's been 2 years.   You may have done a release or 2 since then.
