### ISSUE TITLE
Given a large number of Maildir folders, UI does not display all the mail

### ISSUE THREAD

**Issue by ng-0** [runbox/runbox7#50]
Hi,

I have roughly 30 or more Maildir folders. In the old interface this works perfectly fine.
With runbox7 as running on runbox.com one folder loads all the contained Emails in the folder.
If you switch to another folder (which is not empty), it is displayed as empty.

If it matters: the Browser is Firefox 62.0.3 from pkgsrc on NetBSD.

**Comment by gtandersen** [comment]
@ng-0 Are you using a local/synchronized index? If so, try to stop and restart it using the controls at the bottom of the folder pane. If that doesn't help, please provide your Runbox username (via https://support.runbox.com) and we'll investigate and re-index your account if necessary.

**Comment by ng-0** [comment]
Turning synchronization off bypasses the problem for now.

**Comment by ng-0** [comment]
However, with sync turned off emails open and close again.

**Comment by ng-0** [comment]
Okay, I will do so if it appears again (I'm about to sync a larger number of mails to Runbox soon).

**Comment by gtandersen** [comment]
This appears to no longer be an issue.
