### ISSUE TITLE
"Full height" setting doesn't persist across page reloads

### ISSUE THREAD

**Issue by tadzik** [runbox/runbox7#518]
Clicking the "Full Height" arrow in mailviewer toggles its behaviour for the remainder of the webmail session – but it gets forgetten if the page gets closed and opened again.

It should behave like the rest of the webmail settings (showing side panel, horizontal vs vertical split etc) that get recorded in localstorage.

**Comment by castaway** [comment]
This is also the case for manually set / not full height, email/list height size setting, so yes should probably do this.

I also think (separate issue?) that when using "full height" it would be handy to have a pair of "previous", "next" email arrows, so we can just cycle through the inbox without returning to the list every time.

**Comment by tadzik** [comment]
Seems like a duplicate of https://github.com/runbox/runbox7/issues/429

**Comment by castaway** [comment]
Yup, it does.. fix will apply to both certainly. While we're at it, what about vertical sizing? (when email view pane is on the right, rather than bottom)
