### ISSUE TITLE
Don't show the HTML version of an email as an attachment.

### ISSUE THREAD

**Issue by runboxdave** [runbox/runbox7#521]
It is unhelpful that the message list shows that an email that has a plain text and HTML version shows as having an attachment. While this might be technically correct it is unhelpful in determining which messages have attachments you might want to see as an attachment and which are simply HTML formatted messages with not other attachment of interest.

**Comment by gtandersen** [comment]
This is still an annoyance; increasing priority.

**Comment by castaway** [comment]
This needs fixing in the backend / indexer - we take the "has attachments" flag from the index updates - I'll have a look if I can figure out where..

**Comment by castaway** [comment]
Patches in place for searchindex, backend and runbox7 for this.
