### ISSUE TITLE
Up/down arrow do not work in Runbox7 compose (edit) in text mode

### ISSUE THREAD

**Issue by david-a-wheeler** [runbox/runbox7#522]
When composing a new email in text (non-HTML) mode, the normal up/down keyboard keys do not work. The numpad up/down keys *DO* work if I press the numlock key so that they are interpreted as arrow keys.  The left/right arrow keys and mouse selection do work. This is on latest Firefox + Windows 7.

**Comment by kvviecien** [comment]
I've done a little research and it seems to be a "problem" within the browser settings. 
There's something called "caret browsing", which is an accessibility option that allows you to move throughout the pages without using your mouse. I believe it can somehow change the way users interact with documents and text editors. 
You can turn it on/off pressing F7 or in the browser settings under "Browsing" > "Always use the cursor keys to navigate within pages".  For me it fixed the problem.

**Comment by gtandersen** [comment]
I have seen this issue recently but wasn't able to reproduce it now.

@david-a-wheeler Did the above suggestion resolve the issue for you?

**Comment by castaway** [comment]
This seems to work ok for me in Chrome + Firefox at the moment, any other reports of it?

**Comment by david-a-wheeler** [comment]
It works now!! Thank you very much!
