### ISSUE TITLE
"To" address is null when nickname filled in, but first/last name are not

### ISSUE THREAD

**Issue by david-a-wheeler** [runbox/runbox7#523]
If my contact list has an empty first/last name for an email address, the name shown is "null" EVEN when there is a nickname set. If first and last name are empty, I would expect the nickname to be used (if present) instead of using null. Thanks!

**Comment by castaway** [comment]
Hi, can you reproduce the sequence of events? I've just created a new contact in runbox, with a nickname and an email (no first/last name), and sent an email - it ends up in "Sent" as ```"jrobinson" <jrobinson@blah>``` not null (but also not as the nickname I used).

Was yours an imported contact?

**Comment by castaway** [comment]
It occurs to me you might have meant "name shown" in the contacts list, not in a sent email? (please clarify) .. my created one does show up as "jessr" there, which is the nickname I used.

#313 explains why it wont be used in a sent email "to" field.

**Comment by david-a-wheeler** [comment]
I don't *import* my contacts list, I just use my existing contacts list.

Steps:

1. In Runbox 7, press "Compose" button
2. In "To" field, type in a contact nickname without first/last name. E.g., I have a mailing list whose email address and nickname begin with "mason-..." and have no first for last name. It shows correctly from the dropdown list, so I select it.
3. I see that the fill in for the "To" field has a highlighted name of `null <mason-...>`. Note that I have *NOT* sent the email address, but the "to" information is clearly not right. It's the "null" in the name that seems wrong to me. The actual email address in `< ... >` is fine.

I hope that helps.

**Comment by castaway** [comment]
Thanks! Weirdly, today I can reproduce it. I'll see if I can figure out whats up with it

**Comment by castaway** [comment]
Fixed in #561
