### ISSUE TITLE
Message error when message has been moved and not using local index

### ISSUE THREAD

**Issue by runboxdave** [runbox/runbox7#526]
If a message is moved (from the Inbox in this case) and you are not using the local index the message list is not updated and selecting the message gives the error below.

{"status":"error","errors":["message_could_not_be_found"]}

**Comment by gtandersen** [comment]
@davidbowdley Could this be caused by delays (either network or server) and the message simply takes longer to move (or fails entirely)? 

I was not able to reproduce this in production.

**Comment by davidbowdley** [comment]
The messages had been moved quite some time before. I only happened to stumble upon the problem and wasn't specifically looking for it. It seemed like a failure of the message list to update as refreshing the page or changing folder and then back to the Inbox fixed the issue.

**Comment by gtandersen** [comment]
@davidbowdley Is it reproducible currently?

**Comment by davidbowdley** [comment]
I think there was some crucial information missing for this issue. I think the messages were moved using IMAP and the web app hadn't updated. It might be reproducible.

**Comment by gtandersen** [comment]
See also internal issue 1169.

**Comment by gtandersen** [comment]
This should be resolved now.
