### ISSUE TITLE
Can get stuck in empty "compose" window

### ISSUE THREAD

**Issue by castaway** [runbox/runbox7#528]
1) Start with no drafts
2) Compose a message, save as draft or wait for it to auto-save
3) While in same window, hit the trashbin / delete draft icon
4) Now you are still on the /compose?new page, and cannot "compose" a new message

I think after using the delete draft icon from the /compose?new page, the user should be sent back to plain /compose (or somewhere else useful)

**Comment by gtandersen** [comment]
@castaway Agreed!

**Comment by castaway** [comment]
Looking into this, while I'm poking it - would it also be logical that if you view a contact, and hit the "email this contact" button, and exit the draft, you should be returned to the contact page?

Is there anywhere else (other than reply / forward) that a new draft can be started from?

**Comment by gtandersen** [comment]
Yes, it makes sense to return the user to the screen they originated from.

I don't think there are other ways for a new draft to be started than those mentioned.

**Comment by castaway** [comment]
Merged.
