### ISSUE TITLE
Add option in individual folder menus to create a new sub-folder

### ISSUE THREAD

**Issue by davidbowdley** [runbox/runbox7#532]
Although creating a new sub-folder is possible by clicking on a folder and using the + icon at the top of the folder list it would be useful and more ergonomic to also have an option in the folder menu where you can rename/delete folders.

**Comment by vertigo220** [comment]
To clarify, the add folder pop-up that shows when clicking the plus button should show the folder tree and allow the user to select where in the tree the new folder should be placed, i.e. under the selected branch.

**Comment by kvviecien** [comment]
Fixed in #565
