### ISSUE TITLE
Close email when unchecking

### ISSUE THREAD

**Issue by vertigo220** [runbox/runbox7#542]
When unchecking/deselecting an email, i.e. clearing the check box that's automatically checked when an email is opened, it should optionally close the email, as an alternate way of doing so vs clicking the x button at the top-right.

**Comment by gtandersen** [comment]
@vertigo220 How would you suggest that option be presented?

**Comment by vertigo220** [comment]
Are you asking how it should be done or how it should be offered to the user as an option to enable or disable, i.e. choose whether they want that behavior?

**Comment by tadzik** [comment]
This brings up a good point, and a somewhat annoying discrepancy between what is selected and what is displayed.

When an email opened (by clicking on it), it also becomes selected. However, selecting an email does not open it.

When an email is closed, it becomes de-selected. But de-selecting an email, as @vertigo220 says, it does not become closed.

With multiple selections it gets outright awkward: while an email is opened you can select more emails: but only the original one is displayed then. When you close it, everything becomes de-selected -- so maybe it should not have been selectable in the first place?

I suggest we agree on some consistency here and hopefully eliminate the unexpectedness that @vertigo220 experienced -- while technically we don't have a feature that would close the email when it's de-selected, the UI seems to heavily imply that this is how it ought to work.

**Comment by tadzik** [comment]
A possible solution (design-wise, aside of implementation details) would be to always have an email being selected mean that the same email is being displayed – and vice versa. This cuts all the confusion when a single email is involved, but may become problematic with multiple emails. We could display a summary of the selected ones on the email preview pane, possibly with some message actions: that would be even handy. But what if the user is not using the always-open preview pane and also uses the horizontal preview? Then as soon as they start selecting multiple emails to move/delete, a mailviewer opens up, takes up half the screen space and maybe even interrupts the selection process itself (at the very least it becomes confusing and annoying). I'm not sure if solving this elegantly is possible without a careful redesign of the webmail layout and its dynamicness – but maybe it's worth it. We could also distinguish between selecting a single email and selecting multiple (so: only opening the mailviewer when the mouse button is released). This avoids the issue of the horizontal mailviewer popping in mid-selection, but still has a flaw of taking away the screen estate that the user might need to keep selecting more stuff.

Ideas?

**Comment by castaway** [comment]
My inclination would be "dont check the selected box when an email is opened".. keep that for operations across multiple emails..

**Comment by castaway** [comment]
See also: https://github.com/runbox/runbox7/issues/10#issuecomment-582427348 which would require separation of checkboxes, and "which message is open"

**Comment by gtandersen** [comment]
Agree that opening and selecting messages are distinct actions.

**Comment by vertigo220** [comment]
@tadzik put it very well, though if I'm understanding this correctly:

"A possible solution (design-wise, aside of implementation details) would be to always have an email being selected mean that the same email is being displayed"

I would have to disagree with that. I absolutely don't want an email to display when I select its checkbox, as that would mark it as read and also allow any tracking images in it to work. I only like emails to display when I actually click on them specifically to show them. When checking them, they should just be checked or, perhaps even better, each checked email could show as a narrow strip with just the header info (from/to/subject/date) in the preview pane, making it easy to see what emails are selected as you scroll through the folder. Sort of like how Fastmail does it but not stacked.

**Comment by castaway** [comment]
excellent, glad we're all of the same opinion (well apart from tadzik's musings..)

**Comment by tadzik** [comment]
I don't mind selecting being completely detached from opening – they ought to be separate things, imho. I merely wondered about a possible solution for if we want them to be more or less equivalent :)

So keeping that in mind, I think we can consider:

- emails being selected when they're open to be a bug, and therefore...
- emails not closing when unselected to not be a bug (which makes this issue closable as invalid)

Is that what we've decided on here?

**Comment by vertigo220** [comment]
Well, it wasn't meant to be a bug report, rather a feature request, and if we close the issue, we close the discussion regarding changes to message selection vs opening, which is still pertinent, so if anything I think the title should be changed, but I don't think it should be closed.

**Comment by castaway** [comment]
The checkbox handling is being sorted under the fixing of #10, #11 and #303.. I'n ok to leave this open and tag it as well.

**Comment by vertigo220** [comment]
I'd say #11 is different from the rest, and #10 and #303 are duplicates of each other and, yes, this one is similar to those, only it goes into more detail about the problem and actually proposes the opposite solution due to approaching from a different angle. So I'll comment on #10 and close this one.
