### ISSUE TITLE
Layout suggestions re more efficient space usage (condensed mode)

### ISSUE THREAD

**Issue by vertigo220** [runbox/runbox7#550]
The space is used rather inefficiently. For starters, the top blue bar is taller than it needs to be, and has a lot of empty space that could be used for other things, especially if a lot of the current items were organized better, such as putting webmail, contacts, calendar, files, and settings in a menu and/or showing icons only. Actually, subscribe (which, granted, wouldn't be there on a normal account), help, and blog could be put in the same menu. In any event, changing that up and making the bar about half its current height would make it take up less space and provide plenty of space within it for other things, such as the search bar--which would free up space in the message list for actual messages--and perhaps the icons as mentioned in issue #11.

Another waste of space is the "Good evening...Welcome to Runbox 7..." message above the folder list, which should be able to be dismissed. And the folder list itself could also be compacted by quite a bit, as there's currently quite a bit of space between items, not to mention the folder names themselves are quite large, which I realize is great for some people, but between that and the significant spacing between them, means I would find it annoying having to scroll up and down to access various folders, when there should be enough space for them to all be visible at once, assuming the space were used better.

As for the message list itself, there should be options to adjust how compact it is, as each line item (message) is much taller than needed to display the information contained within, and they could easily be resized to 75% height and still have adequate spacing, i.e. not have the messages all crammed into each other. The messages themselves (far-right pane) also don't use space as efficiently as they can, though not as badly and that's not as important as the other areas.

**Comment by gtandersen** [comment]
Thanks for the suggestions @vertigo220 -- we will certainly consider adding a "condensed" mode for power users.

**Comment by gtandersen** [comment]
Since this issue was created we have implemented a condensed main menu:

<img width="1193" alt="Runbox 7 regular" src="https://user-images.githubusercontent.com/1620058/132576046-9a4c6834-6c80-4ef9-a78a-54976515d056.png">

The following screenshot present progress on a further condensed layout with smaller font sizes and folder entries:

<img width="1193" alt="Runbox 7 condensed" src="https://user-images.githubusercontent.com/1620058/132576054-93e722d2-de3a-4a7e-a42c-7dc5c69c914f.png">

**Comment by gtandersen** [comment]
New and improved version:
<img width="1185" alt="Runbox 7 Condensed 2" src="https://user-images.githubusercontent.com/1620058/143261957-cc1d6d5c-cd2f-4151-ad99-0ec75280afed.png">

**Comment by gtandersen** [comment]
Condensed Draft Desk:

<img width="1189" alt="Runbox 7 Draft Desk Condensed" src="https://user-images.githubusercontent.com/1620058/143293246-9451dbee-4839-4f46-82fe-fec1ab10ab0a.png">

**Comment by gtandersen** [comment]
These improvements have now been implemented in #1149.
