### ISSUE TITLE
Layout stored across browsers and sessions

### ISSUE THREAD

**Issue by castaway** [runbox/runbox7#560]
A minor niggle yet a bit annoying - I've opened runbox7 several times now on various browsers/backends, and each time had to re-tell it "nope, the preview pane goes below the email, not to the side" - could we save this on the backend?

**Comment by gtandersen** [comment]
That could be an option, however a user might wish a different layout on a smartphone than a laptop for instance.

**Comment by castaway** [comment]
Tis true.. maybe that would be one of the options ;) So far it's only been one tweak, to be fair. I've not attempted to view it on a mobile device yet..

**Comment by gtandersen** [comment]
The ideal solution might be to store such settings on the server but per device (as an option) to allow for differing preferences depending on type of device/client.
