### ISSUE TITLE
Cache contacts locally for use with Compose

### ISSUE THREAD

**Issue by gtandersen** [runbox/runbox7#595]

**Comment by tadzik** [comment]
I couldn't reproduce the slowness you mentioned, but noticed something relevant (and possibly related):

Opening Runbox7 in a new browser, compose doesn't autocomplete anything at all. Even after going to contacts (and verifying that all contacts are indeed there) and back, nothing shows up in compose at all. Only after enabling the search index contacts get autocompleted ­– the ones from the Contacts, that is. So it seems like with the absence of searchindex, the compose form doesn't search the searchindex (obviously), but then it doesn't even attempt to gather results from contacts.

Could this be the same issue you noticed, or is there more to investigate here?

**Comment by gtandersen** [comment]
@tadzik I realized from your comment that the recipient list is (still) built from the index and not the Contacts database, and that probably explains the issue as I have upwards of 400k messages in the index. 

The solution seems to be switching to the Contacts list if feasible. :)

**Comment by kotecky** [comment]
> The solution seems to be switching to the Contacts list if feasible. :)

A user's comment on this: Using the Contacts is of course a necessity, using an index based on the in/out-box is a good feature. I guess the users will prefer a mix of both, and ideally displayed not in an alphabetical order but taking into account the frequency of use: when typing in letters of a name. Often when typing a contact's name, other names much less used are always sitting on top. This is annoying mainly on a mobile phone where there is less space in the interface and one needs to scroll. 

One danger of the index of in/out-box is the presence of addresses that do not exist (closed accounts, typos) and irrelevant ones.

**Comment by castaway** [comment]
> @tadzik I realized from your comment that the recipient list is (still) built from the index and not the Contacts database, and that probably explains the issue as I have upwards of 400k messages in the index.
> 
> The solution seems to be switching to the Contacts list if feasible. :)

It is actually built from both, but only updates from either if the search index changes - I'm working on separating that, so that its updated if/when either changes.

**Comment by gtandersen** [comment]
@castaway What is the status of this issue? I think it would be useful if the CardDAV database is queried and displayed first, instead of waiting for the search index since that can take longer.

**Comment by castaway** [comment]
The separation is complete.. the list is now composed of both contacts, and index recipients, and updated when either one changes (not just when/if the index changes)

**Comment by gtandersen** [comment]
@castaway This doesn't seem to improve the responsiveness of the recipient autocomplete though. There is still considerable latency with a sizeable index.

**Comment by castaway** [comment]
Then I guess we need more enhancements. Could do with some stats (and test indexes)

**Comment by tadzik** [comment]
@gtandersen is it any better currently, with the index improvements in place?

**Comment by gtandersen** [comment]
@tadzik Indeed, it seems much faster now! :)

**Comment by castaway** [comment]
@gtandersen Can we close this one?

**Comment by gtandersen** [comment]
Yep!
