### ISSUE TITLE
Expand HTML editor with more functionality

### ISSUE THREAD

**Issue by gtandersen** [runbox/runbox7#6]
In the HTML editor, add buttons for create/edit link, (un)ordered list, font face, etc.

**Comment by petersalomonsen** [comment]
This would be customization of the tinymce config here:

https://github.com/runbox/runbox7/blob/master/src/app/compose/compose.component.ts#L294

**Comment by gtandersen** [comment]
Thanks @petersalomonsen! 

@davidbowdley @kservik Which items would we like to support in the HTML editor? 

Ref: https://www.tiny.cloud/docs/demo/basic-example/, https://www.tiny.cloud/docs-3x/reference/buttons/

**Comment by davidbowdley** [comment]
@petersalomonsen I think coloured text, bullet points lists and making something a hyper-link are the obvious ones to add. I see that other formats are available in a menu in Runbox 7, but I would include underline as a button perhaps.

Some common font options might also be nice.

**Comment by gtandersen** [comment]
Another request for buttons like lists, text size, text color, and code:

https://community.runbox.com/t/compose-insert-link/955
