### ISSUE TITLE
Mail: inline images not to be displayed among attachments

### ISSUE THREAD

**Issue by kotecky** [runbox/runbox7#616]
Images used within the body of the email are visible among the attachments. Such images are typically used as images inserted in the email or in the signature, senders and addressees. They pollute the view, cause the message list to incorrectly display that there is an attachment, and implementation of a search among messages by presence of an attachment. 

Such inline attachments/images should not be displayed at the end of the email. (e.g. Mozilla proceeds this way, https://support.mozilla.org/en-US/kb/configuration-options-attachments)

**Comment by castaway** [comment]
This has been fixed
