### ISSUE TITLE
Mail: attachment display 

### ISSUE THREAD

**Issue by kotecky** [runbox/runbox7#626]
When attaching a file to an email, the file is being uploaded to the server first, the duration of the action is witnessed by a progress-bar. When completed, the bar disappears. After that, the there is a blank when the users may think that the upload failed. Only several seconds later (even as many as 10) the attachment name and size appears. 

Ideally, there would be a no blank between the two indications.

**Comment by gtandersen** [comment]
See also #634 and #1070.

**Comment by castaway** [comment]
We improved the attachment upload as a fix for #1070 - does this look better, @kotecky  ?

**Comment by kotecky** [comment]
Yes, the time gap is shorter, now (on notebook on a quick network - is it linked at all?) about 1 second. Tested with files of various sizes.

**Comment by gtandersen** [comment]
The time it takes for an attachment to upload and display will vary with size and bandwidth, yes.

This now appears resolved; closing issue.
