### ISSUE TITLE
Spam and Trash folders show incorrect 0 count

### ISSUE THREAD

**Issue by tadzik** [runbox/runbox7#633]
Reported on https://community.runbox.com/t/spam-and-trash-folders-show-incorrect-0-count/1228

Introduced by https://github.com/runbox/runbox7/pull/513

Trash and Spam are not indexed, and so their folder counters are all wrong if the searchindex counting mechanism in use. We should at the very least fallback to the server info for these two.

However, I do remember some previous discussions about indexing at least Trash. @gtandersen, do you remember?

**Comment by gtandersen** [comment]
Agree that we could fall back to the server counts for these folders as long as it doesn't impede performance.

This is the issue regarding optional indexing of Trash: #290
