### ISSUE TITLE
Mail: display of attachment progress

### ISSUE THREAD

**Issue by kotecky** [runbox/runbox7#634]
When attaching an email, the progress of the upload is displayed. Then it disappears for a while (can be as long as 10 seconds) until the message showing the attached file/s including their size appears. 

Ideally, there should always be a message so as the user has no doubts about the status.

**Comment by gtandersen** [comment]
@kotecky This sounds like a possible duplicate of #626?

**Comment by kotecky** [comment]
@gtandersen Right, good catch, sorry.
