### ISSUE TITLE
Differentiate "Recently used" contacts from recipients 

### ISSUE THREAD

**Issue by gtandersen** [runbox/runbox7#661]
The "Recently used" contacts on Compose look identical to the actual recipients, which might be confusing as they could be interpreted as recipients too. 

If they were made slightly smaller and perhaps indented or shown in a subtly different color they would be more easily distinguishable.

**Comment by gtandersen** [comment]
This looks much better, but makes me realize that perhaps the actual recipients should be blue and the suggested recipients gray... 

In order to not cause more confusion, we could at the same time slightly decrease the font size of the latter?

**Comment by tadzik** [comment]
> perhaps the actual recipients should be blue and the suggested recipients

Hah, the customer report suggested them to be blue in order to resemble links more :)

**Comment by kvviecien** [comment]
I switched the colors, also made the gray a little lighter (making it the side-bar hover color).

> In order to not cause more confusion, we could at the same time slightly decrease the font size of the latter?

Font sizes throughout the whole page are pretty consistent and making the font smaller disturbs the view a little. Lighter gray also makes the suggestions a bit less prominent, so maybe that could be enough. 
I will also try to think about other ways to deal with the look of suggestions.

**Comment by gtandersen** [comment]
Very good, and I see the point regarding font sizes. 

The design goal is for there to be no room for confusion about which recipients the message is being sent to.

**Comment by gtandersen** [comment]
In a recent deployment both actual recipients and suggested recipients are light blue. To differentiate, the suggested recipients can now be made gray.

**Comment by kvviecien** [comment]
Something probably got overwritten; the suggested recipients were set up to be gray. Thank you for the fix :)

**Comment by gtandersen** [comment]
No problem -- closing issue.
