### ISSUE TITLE
Need to refresh browser when creating new folders and subfolders

### ISSUE THREAD

**Issue by Backspaze** [runbox/runbox7#670]
When I create a folder I need to refresh the browser tab before being able to fully use the folder or switch between different subfolders.

OS: Windows 10 1909 (18363.900)
Local index: Yes
Browser: Firefox 78.0.2 (64-bit) and Chromium 81.0.4044.138 (Developer version) (64 bit)

Steps to reproduce:

1. Go to Webmail
2. Click on + to create a new folder/subfolder, give it a name and click the check mark to create it
3. The folder gets created but instead of showing number of items and the three dots there's just a text saying "more" and nothing happens when you click on the "more" text
![bild](https://user-images.githubusercontent.com/12255362/87562201-ffbe4680-c6bd-11ea-9913-044a0fa32911.png)
4. If I try to expand another folder to view its subfolders nothing happens (this step is somewhat inconsistent)
5. Switching between root folders to view their contents seem to still work while in this state
6. Refresh the page and everything should works correctly again

**Comment by gtandersen** [comment]
Thanks for this detailed report, @Backspaze.

This issue could be related to #506.

**Comment by kvviecien** [comment]
Fixed
