### ISSUE TITLE
Make sure links and URLs in emails are clickable as hyperlinks

### ISSUE THREAD

**Issue by runboxdave** [runbox/runbox7#685]
Make sure links and URLs in emails are clickable as hyperlinks. Sometimes this is not the case and perhaps the interface is relying on the web browser to perform this function? I'm not sure and comments from a developer would be useful.

**Comment by gtandersen** [comment]
@davidbowdley It depends on the chosen format of the message view (HTML vs plain text) and the format of the link in the plain text version (if available). 

For instance it seems the link is not clickable if there are other parameters between `<a` and `href`.

**Comment by castaway** [comment]
Do we have any specific examples of this handy?

**Comment by davidbowdley** [comment]
I'll see if I can come across one and copy it to the test account.

**Comment by gtandersen** [comment]
Ensure that links are not enclosed in square brackets, ref. support ticket OQI-791-94740.
