### ISSUE TITLE
Not all message show in local index Inbox due to difference in folder case

### ISSUE THREAD

**Issue by runboxdave** [runbox/runbox7#69]
Some messages do not appear in Inbox as their assigned folder is INBOX. 

Searching for the message works, and using the search: `folder:INBOX OR folder:Inbox` show all messages.

Therefore the proposed solution is to modify the query that is used to list the Inbox content.

The problem is reproducible by moving a message from any folder to the Inbox via IMAP.

**Comment by gtandersen** [comment]
See internal issue 978 for the IMAP problem.

**Comment by gtandersen** [comment]
Is this still reproducible @runboxdave?

**Comment by runboxdave** [comment]
@gtandersen I don't know as it is more than 2 years since this was raised and I don't recall who reported the issue.

**Comment by gtandersen** [comment]
Ok; looks like it was fixed above so closing the issue.
