### ISSUE TITLE
Reloading /#Inbox:XXXX doesn't display the email in horizontal preview mode

### ISSUE THREAD

**Issue by castaway** [runbox/runbox7#702]
Refreshing a page showing an email, when the display is in horizontal mode, doesn't re-display the email..

**Comment by tadzik** [comment]
FWIW, the same thing causes our e2e tests to fail. SingleMailViewerComponent is instantiated dynamically with an `ngIf`, and sometimes (apparently always in horizontal mode) it pops into existence later than the URL parameter is being checked.
