### ISSUE TITLE
Deleting multiple messages resulted in an empty message list

### ISSUE THREAD

**Issue by runboxdave** [runbox/runbox7#713]
I selected and deleted a number of messages and after the delete option the screen that was returned was empty of messages. I waited but nothing happened. However, when I touched the screen the message list appeared. It would seem that the screen just needed to refresh.

**Comment by gtandersen** [comment]
Confirmed that this happens intermittently, but no reliable pattern detected yet.

**Comment by castaway** [comment]
The "deleteMessages" action doesn't seem to do anything that triggers an immediate screen update, so it would end up waiting on the next index refresh, I think. (which could be 10secs away)

**Comment by gtandersen** [comment]
It does trigger an immediate update when the local index is in use, but not otherwise.

**Comment by gtandersen** [comment]
@davidbowdley Did this occur while using the local index?

I have reproduced a similar symptom where the message list disappears beneath a message that is deleted (with local index), but it doesn't happen consistently. I then have to click to another folder and then back again for the entire list to be displayed.

On closer inspection it appears that when you delete a message, a blank full height box is inserted in place of the deleted entry and the vertical scrollbar disappears. When you scroll down, the next messages appear beneath this blank box.

**Comment by gtandersen** [comment]
Another symptom that appears to correlate is that the padlock symbol in the URL bar is broken (seemingly insecure elements). A forced reload of the app appears to resolve both symptoms until it occurs again.

**Comment by gtandersen** [comment]
Further information: It appears the problem might be redrawing the entries beneath the deleted ones, as those entries sometimes appear after a short delay.

**Comment by gtandersen** [comment]
Check for console errors when this happens.

**Comment by gtandersen** [comment]
Probably related to one of these commits: 

https://github.com/runbox/runbox7/commits/master/src/app/canvastable/canvastable.ts

**Comment by gtandersen** [comment]
This continues to happen and there are no errors in the console. Just seeing the usual `Getting latest messages from server` and other typical output.

**Comment by gtandersen** [comment]
This continues to happen intermittently, i.e. deleting or moving messages doesn't successfully update the message list and the message list is stuck either with no change at all or a partially empty message list.

**Comment by gtandersen** [comment]
It does not appear related to performance on the local device, but possibly response from REST servers.

**Comment by gtandersen** [comment]
See also internal issue 1156.

**Comment by gtandersen** [comment]
This is also reported in smaller accounts, ref. support ticket DUY-755-41975.

**Comment by castaway** [comment]
Does this happen in/from specific folders? With search index on or off?

**Comment by gtandersen** [comment]
@castaway Typically happens in Inbox as it's the folder most commonly used (but most likely not limited to any particular folder) and local index is in use.

The observed sequence of events is normally as follows:

1. Delete or move one or more messages in the list.
2. The message(s) disappear, as do the remainder of the list (all messages beneath the selected one(s) before the list is redrawn. 
Normally this happens so fast that it can't be detected, but at times the process is slower and an empty portion of the list can be seen for a short time. Sometimes the rest of the list isn't redrawn at all and that is when it results in an empty message list.
3. Once the list is redrawn correctly, a small spinner appears in the bottom right corner indicating background processes (as indicated by console output).
4. After the above is completed, the unread message counters flash briefly with updated counts.

The only observed event should really be that the message list is always immediately redrawn, and that only the affected folder counts update (i.e. source and target folders).

See also internal issue 1156.
