### ISSUE TITLE
Domains can be set to auto renew in both Runbox 6 and 7 and this shouldn't be possible

### ISSUE THREAD

**Issue by runboxdave** [runbox/runbox7#716]
Domains currently can't be renewed automatically and must be renewed manually. However, the interfaces in Runbox 6 and 7 both show domain products can be set to auto renew. This is confusing.

**Comment by tadzik** [comment]
In the pipeline in https://github.com/runbox/runbox7/pull/723 and on the backend

**Comment by tadzik** [comment]
@davidbowdley can you verify that this is fixed live?

**Comment by castaway** [comment]
@runboxdave could you test/check this one? it seems it was fixed years ago.. (reopen if not)
