### ISSUE TITLE
When editing an identity or alias move delete button out of the top menu

### ISSUE THREAD

**Issue by runboxdave** [runbox/runbox7#732]
When deleting an identity or alias you have to do an extra click to see the delete option which is hidden under the menu at the top of the pop-up box. It would be easier if this was placed at the bottom with the Save and Cancel buttons but over to the right so it can't be accidentally clicked. Perhaps there should be a confirmation dialogue too.

**Comment by castaway** [comment]
Seems to have been done at some point
