### ISSUE TITLE
New message is sent as previous draft version

### ISSUE THREAD

**Issue by gtandersen** [runbox/runbox7#744]
Sometimes a newly composed message is sent using the previously saved version of the draft (from the same session). This means that the most recent change to the message content is sometimes not included in the sent message.

The issue seems to occur in the PWA only, but regardless of whether wifi or mobile broadband is used.

**Comment by castaway** [comment]
impressive, any clues on how to replicate that, or does it seem random?

**Comment by gtandersen** [comment]
Seems rather random aside from using a slow connection, and sending the message right after making some changes.

**Comment by gtandersen** [comment]
Have not seen this issue in recent memory.

**Comment by gtandersen** [comment]
Closing this as it is no longer occurring.
