### ISSUE TITLE
Browser security indicator changes status and message actions have no effect

### ISSUE THREAD

**Issue by gtandersen** [runbox/runbox7#789]
Sometimes the security indicator (padlock) in the browser address bar changes status to indicate that parts of the page are insecure. 

At the same time, and possibly as a consequence, message actions have no effect -- for instance, moving messages to a folder does not work.

The page source and the Storage Inspector do not show any insecure sources. No message was open when the below screenshot was made (Firefox 81.0.1 on macOS). 

Only reloading the app resolves the issue.

<img width="351" alt="Parts of the page are insecure" src="https://user-images.githubusercontent.com/1620058/95722384-b6cc4e80-0c28-11eb-82fc-a15fe52f40ec.png">

**Comment by gtandersen** [comment]
Correction: Messages are in fact moved, but the message list isn't updated until the app is reloaded.

**Comment by kvviecien** [comment]
@gtandersen is this still an issue?

**Comment by gtandersen** [comment]
@kvviecien Thanks for following up -- I haven't seen this issue for a long time, so closing it.
