### ISSUE TITLE
Use proper attachment filenames

### ISSUE THREAD

**Issue by gtandersen** [runbox/runbox7#79]
In received messages, show attached files' filename in the browser title bar instead of the attachment number (0, 1, ...) and use this when saving the attachment.

Ref: https://community.runbox.com/t/cannot-save-attachments-with-filenames-containing-special-characters/740

**Comment by petersalomonsen** [comment]
This is not a bug. You'll get the correct filename if pressing the cloud download symbol. If clicking the attachment preview, it will try opening in the browser and then you get the server URL.

**Comment by gtandersen** [comment]
Ok. Changing the category to "enhancement". :)

**Comment by gtandersen** [comment]
Possibly related: When saving as PDF via the print function we get filenames such as: blob/https///runbox.com/5b37c26b-1cd3-e444-a723-ff687663e5a3.pdf

**Comment by gtandersen** [comment]
The browser itself should control how attachments are handled -- for instance in Firefox you can change what the browser should do with each attachment type:

<img width="685" alt="Firefox PDFs" src="https://user-images.githubusercontent.com/1620058/229237677-23099e28-8d85-40b6-b49c-e28bc73775b8.png">

You then get this prompt when clicking on PDF attachments in Runbox 7:

<img width="363" alt="Firefox open" src="https://user-images.githubusercontent.com/1620058/229237724-8727d835-8134-4c7b-8406-05b7d729e67d.png">

However the OP concerned attachment filenames and this seems to be handled correctly now as well, so closing issue. :)

**Comment by kotecky** [comment]
> The browser itself should control how attachments are handled -- for instance in Firefox you can change what the browser should do with each attachment type:

Only part of it is true: the server directs the browser via http headers.
