### ISSUE TITLE
Browser Password AutoFill not supported in R7 Account Settings

### ISSUE THREAD

**Issue by ConnectGrid** [runbox/runbox7#802]
Native Browser Password AutoFill is a safe and secure way of handling passwords. They are stored in a secure way, so this should be a trusted mechanism.

- In Runbox6, password autofill works as expected everywhere.
- In Runbox7, password autofill works on the login screen, but is not working when accessing the Account Settings and being prompted for the main account password.

![image](https://user-images.githubusercontent.com/37279875/97787443-726d0800-1b6f-11eb-8e48-c40df19fcd1a.png)

Users should not be expected to go look up their password every time and copy/paste it when they have one that is cryptic and impossible to remember. Please kindly enable password autofill whenever a password is required.

There seems to be JavaScript/CSS that specifically targets autofill elements and behaviour, so if autofill being deliberately intercepted, please kindly provide an explanation.

Browser: Safari 14.0, macOS 10.15.7

**Comment by ConnectGrid** [comment]
Any thoughts on this? It's still not working.

**Comment by ConnectGrid** [comment]
This issue still exists.

I've also noticed the following discrepancy.

Logged into Runbox 7.

1.  Settings > Account > **Account Settings**
2. Switch to Account Security Tab
3. R6 Modal appears that correctly supports autofill.

But...

1. Menu -- Settings > Account > **Account Security**
2. R7 Modal appears (as per screenshot above) that does **not** support autofill.


It's been four months since I originally opened this issue. I know you guys and gals have a LONG list of items to get through for development, but if you can drop a reason for why autofill might be disabled for the Runbox7 modal, I'd appreciate it. AutoFill is *not* a security concern. If anything, it facilitates stronger security since users don't need to copy/paste their password from an external password store. The browsers inserts it for them. AutoFill should not be overridden to try and protect the user.

In my case, I'm using native Safari and native Keychain integration on a Mac, so not using any 3rd-party utilities. AutoFill should be working properly. Seems that the Angular Material is interfering.

**Comment by castaway** [comment]
Hi, this feature is working for me on runbox.com -> Settings -> Account Security (Account Settings is the runbox v6 one) - I'm using the chrome-based Vivaldi, the password box defaults to blank, when I click in it my browser displays a list of my stored runbox user/pass combos to pick from.

It seems therefore not to be a universal issue, or a deliberate turning off of that feature - I'll hunt for someone with Safari to try it out and report back.
