### ISSUE TITLE
Calendar UI doesn't advertise the way to sync it between apps

### ISSUE THREAD

**Issue by gtandersen** [runbox/runbox7#805]
While RMM7 Contacts has a help function to explain how to sync it with other apps, Calendar does not.

At a minimum, we could add an obvious link to: https://help.runbox.com/using-a-calendar-client-with-caldav/

**Comment by castaway** [comment]
Neither does webmail, to be fair (have to dig in help docs for smtp/imap links etc)

**Comment by gtandersen** [comment]
@castaway That is true, and we should improve upon this as well -- see #816

**Comment by gtandersen** [comment]
New issue #1304 created for the suggestion in #1301; closing this issue.
