### ISSUE TITLE
Fix vertical overlapping buttons on Subscriptions screen

### ISSUE THREAD

**Issue by gtandersen** [runbox/runbox7#821]
The special offer on subscriptions/upgrades page is not mobile friendly (button overlaps text).

See: https://runbox.com/app/account/upgrades

**Comment by tadzik** [comment]
Fixed in 0d9005df5a6f0ff7266e9f511aeab465c8826107 as part of https://github.com/runbox/runbox7/pull/808, along with some collateral fixes to addons screen.
