### ISSUE TITLE
Creating new account - 2 msgs, but Inbox 0?

### ISSUE THREAD

**Issue by castaway** [runbox/runbox7#824]
![image](https://user-images.githubusercontent.com/109990/99374050-110c9f00-28ba-11eb-89f0-a1be1699c9b4.png)

Are the two initial messages not created via the normal mechanism?

The value updates correctly as soon as I read one of the messages

**Comment by gtandersen** [comment]
@castaway Correct, the initial messages are delivered internally and might therefore not register correctly in the counts.

**Comment by gtandersen** [comment]
See also #512.

**Comment by castaway** [comment]
Created a backend patch to force a folder recount after adding internal messages

**Comment by gtandersen** [comment]
This should then be fixed; closing issue.
