### ISSUE TITLE
Make Transactions screen mobile friendly

### ISSUE THREAD

**Issue by gtandersen** [runbox/runbox7#827]
Transactions table becomes too narrow to be readable on mobile and doesn't fit on the screen.

See: https://runbox.com/app/account/transactions

**Comment by tadzik** [comment]
Implemented this in https://github.com/runbox/runbox7/pull/808/commits/c86f18e0591d7e4360cc8517b73b186c93448432, as part of https://github.com/runbox/runbox7/pull/808. Looks like this:

![transactions](https://user-images.githubusercontent.com/86378/103367786-3f3eea80-4ac6-11eb-9d25-28d51935b958.png)

**Comment by kvviecien** [comment]
For me all those items have a lot of white space on the bottom part. I'll try to do some magic here.

<img src="https://i.imgur.com/FqWjaou.png">

**Comment by gtandersen** [comment]
@kvviecien This looks great now, but would be even better without the vertical whitespace. :)
