### ISSUE TITLE
Fix overlapping Shopping Cart icon overlaps

### ISSUE THREAD

**Issue by gtandersen** [runbox/runbox7#828]
The Shopping Cart icon overlaps some page headers (including the shopping cart page itself). Maybe it should be moved to the toolbar, regardless of whether we're on mobile or not?

**Comment by tadzik** [comment]
Moved it to the toolbar in d194ed2263422e921f1a78db707218bf8980a86d, as part of https://github.com/runbox/runbox7/pull/808:

![cartbutton](https://user-images.githubusercontent.com/86378/103368652-6bf40180-4ac8-11eb-8ec4-502d130d6e6f.png)
