### ISSUE TITLE
Make Shopping Cart table mobile-friendly

### ISSUE THREAD

**Issue by gtandersen** [runbox/runbox7#829]
The Shopping Cart table is too narrow to be readable on mobile/small screens.

**Comment by tadzik** [comment]
Fixed in 6c9414750edc388ea0d5d8f2f573b439bed2688b as part of https://github.com/runbox/runbox7/pull/808:

![cart](https://user-images.githubusercontent.com/86378/103370857-3b16cb00-4ace-11eb-9d60-070e3d13ecd0.png)
