### ISSUE TITLE
Make payment method cards mobile friendly

### ISSUE THREAD

**Issue by gtandersen** [runbox/runbox7#830]
The payment method cards are too big, overlap, and don't fit on small screens.

**Comment by tadzik** [comment]
Fixed in 99124e9418f5b5874c345f84ada3bca05fa93dca as part of https://github.com/runbox/runbox7/pull/808:

![cards](https://user-images.githubusercontent.com/86378/103409870-0f94ee80-4b69-11eb-9f06-5aad9e3bdf53.png)
