### ISSUE TITLE
desktop view shown on top of mobile view

### ISSUE THREAD

**Issue by fredblockchain** [runbox/runbox7#832]
Hi guys,
I've started using runbox few weeks ago and I'm having an issue using it on mobile app,

The desktop view is shown on top of the mobile view:

![screenshot](https://github.com/fredbellard/anything/blob/main/desktop%20version%20on%20top%20of%20mobile%20version.png)

I'm using firefow web browser version 83.1.0 on Android 10.0.0 on a Huawei P30 Lite

Cheers
Fred

**Comment by gtandersen** [comment]
This looks like, or related to, #852.

**Comment by gtandersen** [comment]
Is this still occurring @fredblockchain?

**Comment by fredblockchain** [comment]
Hi @gtandersen ,
I tried a few times and it doesn't seem to be occurring any more.
Thanks
