### ISSUE TITLE
App Passwords > Disabled toggle is confusing

### ISSUE THREAD

**Issue by ConnectGrid** [runbox/runbox7#842]
The label on the Disabled toggle does not change when enabling/disabling, so it's unclear what the actual state is. The label remains "Disabled" in both states.

![image](https://user-images.githubusercontent.com/37279875/100674367-df63f100-3319-11eb-8e97-fed57762493c.png)

The fact that it's conventional for "enabled" to be in the "right-most" position is irrelevant.

**Comment by ConnectGrid** [comment]
If anything, the label should be "Enabled", not "Disabled". Then it would make sense.

**Comment by gtandersen** [comment]
This should be fixed and can't be reproduced -- reopen if it is still occurring.
