### ISSUE TITLE
Mail: inbox new mail display inefficiency

### ISSUE THREAD

**Issue by kotecky** [runbox/runbox7#843]
After opening the mail app, inbox with messages should be displayed, new mail information downloaded, then new mail displayed in front of the older messages.

The current state: very soon after the app starts, new mail is displayed for a second, then disappears for a second or more, then is finally displayed again (Win10 FF, Android 8, FF). 

Can be reproduced: yes, if a new mail is in any time after loading the app.
Since when: not a recent change. Since ever?

**Comment by gtandersen** [comment]
I couldn't reproduce this with Firefox on macOS. Is it still occurring for you on Windows 10?

When the local index is used, the app should download and check the server index upon logging in (indicated with the blue progress bar above the message list) and immediately show the state from the previous session. 

Subsequently it should download and synchronize from the server any changes that have been made using other clients (including Runbox 6). This is indicated by the counter in the "snackbar" near the bottom of the page. During this process the message list should be shown, and the message list should be updated with any changes as soon as the synchronization is completed.

**Comment by gtandersen** [comment]
Upon logging in it often takes too long for the synchronization of new incoming/updated messages to start. This interval could be decreased or synchronization could ideally occur immediately.

**Comment by gtandersen** [comment]
See also #912.
