### ISSUE TITLE
Empty Trash does not work

### ISSUE THREAD

**Issue by davidbowdley** [runbox/runbox7#858]
The Empty Trash feature has stopped working.

**Comment by castaway** [comment]
Hmm, not everywhere / for everyone it seems, mine is working, which makes it harder to debug..

**Comment by castaway** [comment]
Hunting around in sentry error list, I see lots of evidence though - 504, 414 and 400 errors preventing deletes - I think we shouuld create an API call for "emptytrash" instead of passing a whole long list of email ids.
