### ISSUE TITLE
Add "Not spam" button 

### ISSUE THREAD

**Issue by gtandersen** [runbox/runbox7#86]
In the designated spam folder, add a "Not spam" button for reporting messages as not spam.

**Comment by petersalomonsen** [comment]
The button is already there (and has been for a while). However will fix another bug that the snackbar when reporting "not spam" is not dismissed.

![skjermbilde 2019-02-17 kl 20 30 49](https://user-images.githubusercontent.com/9760441/52918051-f2e3ca80-32f2-11e9-9599-8f2339ef6360.png)

**Comment by gtandersen** [comment]
It works as long as the spam folder is called Spam, but not when designating a different spam folder in Manager > Filter.

If we can use the designated spam folder instead of the folder name it should work regardless of spam filter setup.
