### ISSUE TITLE
Attachment far below the message body

### ISSUE THREAD

**Issue by kotecky** [runbox/runbox7#883]
Since a long time (or since ever?) and very often, but not always, the attachment tiles render far below the message body, with a white space in between (FF on Win10; not in FF on Android). It keeps causing the "did they forget the attachment?" question. And the need to scroll and scroll and scroll.

**Comment by castaway** [comment]
Looking at attachments, even without a big gap (which I havent yet seen), I think we could do better to display them more obviously - maybe move attachments to the top of the email (with a collapsible title), or add a link that jumps to the attachments in the mail view menu?

**Comment by gtandersen** [comment]
@castaway Agreed; it would be intuitive to list the attachments near the top of the message. Showing previews is also useful, so we could do both.

**Comment by castaway** [comment]
Not sure what you mean by previews in this context?

**Comment by gtandersen** [comment]
@castaway When the attached file is an image, a preview/thumbnail is shown in the attachment area:
<img width="240" alt="Screen Shot 2021-08-11 at 20 14 45" src="https://user-images.githubusercontent.com/1620058/129081702-f9d0df27-fe0e-4a63-9d84-35e9d9a45c2d.png">

**Comment by castaway** [comment]
Shuffling things around a bit and making the attachments collapsible:

Default (closed):
![image](https://user-images.githubusercontent.com/109990/139847975-8baee0b5-b138-436c-b1cf-8ff5e1461ef5.png)

Open:
![image](https://user-images.githubusercontent.com/109990/139848048-763b0c7e-6fd1-4720-8b55-684e994d19a6.png)

I'm thinking the "Show attachments" title could be a row of attachment icons instead?

**Comment by gtandersen** [comment]
Looks good @castaway!

Perhaps the Show Attachments drop-down would be more visible with some color (if only just a blue font color), so that users more easily understand that it's clickable?

**Comment by gtandersen** [comment]
Or as you suggested further down, a row of attachment icons would be neat!

**Comment by kotecky** [comment]
Observer's remarks: 
* whether attachments are displayed or hidden should be a setting, not a behavior. Ideally per device (as different setting needs can be expected on a phone and on a computer. 
* the icons/previews should be much smaller.
* previews should be framed or have a BG color (if blank?)  (some are empty and so invisible)
*  something (icon? text?) should tell the user the type (PDF, image, doc,...) 
* attachment file size is needed. Preferably 3.141 MB (or at least 3 141 kB with a separator every 3 digits) rather than 3141592.

Once done, could the same semantics be used when attaching / composing?

**Comment by kotecky** [comment]
Did the observer forget that there should be a checkbox show/hide inline attachments? There are not many things more disrupting attention than a bunch of logos claiming to be (important) attachments. Anyway, they are likely already rendered as inline images so they can be hidden by defaut.

**Comment by gtandersen** [comment]
@kotecky These are excellent suggestions.

We could also display some generic default attachment icon instead of the gray bounding box for unsupported preview file types.

**Comment by gtandersen** [comment]
To bullet point 1 above, we could show a list of attachments in text format near the top (expandable), and a list of smaller icons near the bottom.

**Comment by kotecky** [comment]
Should the attachment list be open by default with inline attachments hidden by default?

**Comment by kvviecien** [comment]
@kotecky, no. The Attachment list should be closed by default, and the attachment grid on the bottom should be visible. 
When opening an email you should se something like this:
<img src="https://camo.githubusercontent.com/151249a79d6064e6234e34dfc8b336a4a7241d6410b3b0b2d0457cf212f78a2e/68747470733a2f2f692e696d6775722e636f6d2f79314a6e6353522e706e67">

**Comment by kotecky** [comment]
@kvviecien sorry, i was not clear enough - imho it would be better if the (top) attachment list was open by default when attachments present.

Inline attachments/images are very often signature images and as such are most of the time not useful so they could/should be hidden from the attachment lists. This is what Gmail (web), Outlook (web and client) do and i find it meaningful. If ever someone needs an inline attachment, then it can be saved as any image from a browser through a right-click. If for any reason Runbox prefers to have them listed, there could be a checkbox in both lists that would further display inline attachments (which are most of the time not useful and so could be hidden by default). 

Attachment names should be indexed and return search if hit. There should be a checkbox to include only messages with an attachment (search field above the message list). Inline images should be excluded from both. Off-topic, sorry.
