### ISSUE TITLE
Rename Webmail to Mail

### ISSUE THREAD

**Issue by gtandersen** [runbox/runbox7#886]
The main menu item Webmail can be renamed to Mail, which is currently a more common term currently. 

Any references to this item must then be updated accordingly (including documentation).

**Comment by 96RadhikaJadhav** [comment]
@gtandersen Can I work on it?

**Comment by castaway** [comment]
Submit a pull request if you'd like to work on it

**Comment by gtandersen** [comment]
This is implemented.
