### ISSUE TITLE
[unfeature request] remove recently used in compose mode

### ISSUE THREAD

**Issue by eoli3n** [runbox/runbox7#906]
"Recently used" is a feature that most users don't need, but can't be disabled in the UI.
I think that that feature needs to be disabled by default to get a cleaner UI.
If a user needs it (which i really doubt) he may enable it in configuration.

Another alternative is to add a new little button and not a big line on the UI.

**Comment by tadzik** [comment]
It can be disabled with the settings menu available under the gear icon, next to "Good morning/evening" message. That affects them both in the sidebar (next to folders) and in Compose.

I don't blame you for not noticing it though: the settings placement in webmail is non-obvious, and we're working towards improving its discoverability and making various settings a bit less scattered around the app.

**Comment by eoli3n** [comment]
Found, thanks !

**Comment by gtandersen** [comment]
> "Recently used" is a feature that most users don't need, but can't be disabled in the UI.
> I think that that feature needs to be disabled by default to get a cleaner UI.
> If a user needs it (which i really doubt) he may enable it in configuration.

That's a generalized assumption regarding what users may or may not need, and it's incorrect in my personal case.

In any event there is already a solution so this issue can be closed.

**Comment by eoli3n** [comment]
Can you send a mail without that feature ? So this is not a "need".
