### ISSUE TITLE
UI not refresh properly when moving mail to trash/folder

### ISSUE THREAD

**Issue by eoli3n** [runbox/runbox7#907]
just open a mail an click on "move to trash", then i get random bug:

- empty mail list, you need to switch folder and open "inbox"
- the mail is still there, nothing changed
- if you are lucky it worked

Same problem with multiple delete and moving to another folder.

Firefox 85.0.2

**Comment by gtandersen** [comment]
Thanks for the report @eoli3n. 

The symptoms sound similar or related to https://github.com/runbox/runbox7/issues/713.

Can you provide details regarding how many messages (approximately) there are in your Inbox and your account in total? Also, do you see any errors in the browser console when this issue occurs?

**Comment by eoli3n** [comment]
![number](https://user-images.githubusercontent.com/14223657/108963538-8686c900-767a-11eb-967f-6f03b39e285e.png)

Can't reproduce right now. I will retry later.

**Comment by castaway** [comment]
I have a PR which will hopefully fix this

**Comment by gtandersen** [comment]
This issue should improve when we move the REST API to separate, dedicated servers, which is imminent.

**Comment by castaway** [comment]
The PR mentioned above got merged, does the issue still happen?

**Comment by eoli3n** [comment]
It seems solved, thanks !
