### ISSUE TITLE
Maintain checkbox selection on message list update

### ISSUE THREAD

**Issue by gtandersen** [runbox/runbox7#914]
When selecting one or more checkboxes in the message list and the list is updated with new messages before further action is taken, the selected checkboxes are automatically moved up the list accordingly.

Instead, the same checkboxes should remain selected to prevent action to be taken on the wrong messages.

**Comment by castaway** [comment]
We currently track "selected row indexes" (and then convert to message ids where needed) - I'll see if I can invert this, which should sort it
