### ISSUE TITLE
Empty message after login

### ISSUE THREAD

**Issue by eoli3n** [runbox/runbox7#917]
Some mornings when I log in, I get this:

URL is ``https://runbox.com/app/#Inbox``

![inbox](https://user-images.githubusercontent.com/14223657/108963219-1bd58d80-767a-11eb-904a-b50634bcd176.png)

If i click on ``Inbox`` then mail list refresh but not directories. I need to refresh the whole app to get my directory list.

**Comment by gtandersen** [comment]
This looks like the REST API (backend) isn't responding, and we are currently working to improve this by moving it to separate, dedicated servers.

**Comment by gtandersen** [comment]
Is this still occurring @eoli3n?

**Comment by eoli3n** [comment]
TBH, I had some many bugs that I don't use the web app anymore, switched to evolution.

**Comment by gtandersen** [comment]
@eoli3n Thanks for the quick feedback. We have resolved many Runbox 7 issues lately, and are now commencing an intensive development phase to improve the quality of every aspect of the user interface.

It would be greatly appreciated if you would be able to check whether this issue still persists for you. :)

**Comment by eoli3n** [comment]
Problem is that the bug was random, hard to test without using in a daily basis.
For what I remember, I didn't face that issue lately, so maybe it's fixed.

**Comment by gtandersen** [comment]
Thanks for the reply @eoli3n -- closing the issue for now.
