### ISSUE TITLE
Addresses in message header are links to open contacts and add the contact

### ISSUE THREAD

**Issue by runboxdave** [runbox/runbox7#938]
The addresses in headers are links to add the address to your Contacts and as such you can't do much else with them such as copy and paste them. This doesn't need to be the case as only the icon at the end of the address needs to be a link.

**Comment by gtandersen** [comment]
This should be fixed now, as per screenshot:
<img width="479" alt="Message headers" src="https://user-images.githubusercontent.com/1620058/150689472-89597478-0dd8-49f1-bd52-834702a0e3ad.png">
