### ISSUE TITLE
Image glitch on retrieve manager screen

### ISSUE THREAD

**Issue by tomearly** [runbox/runbox7#98]
Browser: Chrome 72
OS: Mac OS 10.4.4
URL: https://runbox.com/mail/fetch

Images not appearing as expected.

<img width="443" alt="Screenshot 2019-03-11 at 19 08 29" src="https://user-images.githubusercontent.com/2641244/54151007-be66b880-4431-11e9-8c74-0641eca83daf.png">

Also 

<img width="591" alt="Screenshot 2019-03-11 at 19 18 11" src="https://user-images.githubusercontent.com/2641244/54151441-b8250c00-4432-11e9-9d64-a92461356bcd.png">

**Comment by gtandersen** [comment]
The images should have a blue background when the corresponding section is selected (which on the Manager main screen conceptually includes all three levels).

We will review Manager as part of the ongoing upgrade to Runbox 7.
