### ISSUE TITLE
No subscriptions (products) causes the Active Subscriptions page to fail to complete.

### ISSUE THREAD

**Issue by runboxdave** [runbox/runbox7#982]
If an account for some reason has no subscriptions this page https://runbox.com/app/account/renewals doesn't complete loading and the "spinner" just continues indefinitely.

**Comment by gtandersen** [comment]
@runboxdave Can we reproduce this in a test account?

**Comment by castaway** [comment]
How does an account manage to have no subscriptions ... ?

**Comment by gtandersen** [comment]
This is reproducible in the test1 account in the dev environment.
