### ISSUE TITLE
Allow date periods and ranges in combination with other search expressions

### ISSUE THREAD

**Issue by gtandersen** [runbox/runbox7#986]
When combining date periods (such as YYYY or YYYYMM) with other expressions results are inconsistent and limited, and appear to depend on the order of the expressions.

Additionally it would be useful to search for date ranges, e.g. 20220101-20221231 or 2022-2023.

**Comment by castaway** [comment]
These don't seem to work for me at all, according to the docs, ranges should be like:
`date:20221201..20221210` which inputs did you make work?

**Comment by gtandersen** [comment]
I think custom date ranges are not yet supported by our implementation -- in the above I used e.g. `date:YYYY` to return a year's worth of messages.

**Comment by gtandersen** [comment]
Confirming that date:startDate..endDate does not work, which also affects the range selector in [Overview](https://runbox.com/app/overview).
