### ISSUE TITLE
Titles and URLs in "Subscriptions & Payments"

### ISSUE THREAD

**Issue by runboxdave** [runbox/runbox7#990]
"Your Subscription"s goes to a page called "Account products" 

"Payment Cards" goes to a page called "Your credit cards" which may not be inclusive of all kinds of payment cards (not even the majority in circulation) and so it might be better if it is also called "Payment Cards" for consistency. The URL could also be updated as it is currently /credit-cards

**Comment by kvviecien** [comment]
@runboxdave apart from the link update, is there anything else that has to be done still? Looks like we covered it over the time.

**Comment by runboxdave** [comment]
@kvviecien The URL for "Payment Cards" is still /credit_cards which is a minor point but more debit cards are in circulation than credit cards (by far) and so it is probably worth changing to /cards or /payment_cards to avoid any possible confusion.

The subscriptions title and URL now match :)
