### ISSUE TITLE
Payment Cards page additional information.

### ISSUE THREAD

**Issue by davidbowdley** [runbox/runbox7#994]
For most people the Payment Cards page will mostly be empty. We could include some of the information here:

https://runbox.com/price-plans/payment-methods/

Or link to the page (or both).

**Comment by gtandersen** [comment]
@davidbowdley Can you specify the exact text you think we should include? :)

**Comment by gtandersen** [comment]
This is done:

<img width="831" alt="Paymente Cards" src="https://user-images.githubusercontent.com/1620058/122653094-536bb800-d0f7-11eb-9aef-58c656e5ee3c.png">
